/**
 * Citadel paint catalogue, extracted from CitadelPaintingSystem.pdf (Games Workshop).
 *
 * GENERATED — do not hand-edit. Regenerate with `scripts/extract-citadel.py` followed by
 * `scripts/generate-catalogue.py`; those files document the page formats they read, the
 * exclusions they apply, and how the colours are obtained.
 *
 * Committed rather than built, because it is derived once from a PDF the repository does
 * not contain. It is source data for the app, not a build artefact.
 *
 * WHAT THESE COLOURS ARE, precisely: the swatch colours printed in the catalogue. They
 * are the manufacturer's own print renderings, not spectrophotometer readings of dried
 * paint. Good enough to say "this bottle is in the right area", not good enough to treat
 * as colorimetric truth — see D40 and D44 in the spec, and the caveat the UI shows.
 */

import type { Paint } from './types.ts'

export const CITADEL_PAINTS: readonly Paint[] = [

  { brand: 'Citadel', ref: 'ABADDON BLACK', name: '', range: 'Painting System', hex: '#010101' },
  { brand: 'Citadel', ref: 'ADMINISTRATUM GREY', name: '', range: 'Painting System', hex: '#9da099' },
  { brand: 'Citadel', ref: 'ALAITOC BLUE', name: '', range: 'Painting System', hex: '#3f5787' },
  { brand: 'Citadel', ref: 'ALTDORF GUARD BLUE', name: '', range: 'Painting System', hex: '#364c97' },
  { brand: 'Citadel', ref: 'ASTORATH RED', name: '', range: 'Painting System', hex: '#962f28' },
  { brand: 'Citadel', ref: 'AVERLAND SUNSET', name: '', range: 'Painting System', hex: '#eab825' },
  { brand: 'Citadel', ref: 'BALOR BROWN', name: '', range: 'Painting System', hex: '#845e17' },
  { brand: 'Citadel', ref: 'BANEBLADE BROWN', name: '', range: 'Painting System', hex: '#92816d' },
  { brand: 'Citadel', ref: 'BUGMAN\'S GLOW', name: '', range: 'Painting System', hex: '#7e5247' },
  { brand: 'Citadel', ref: 'CADIAN FLESHTONE', name: '', range: 'Painting System', hex: '#b77855' },
  { brand: 'Citadel', ref: 'CALEDOR SKY', name: '', range: 'Painting System', hex: '#4c6898' },
  { brand: 'Citadel', ref: 'CALGAR BLUE', name: '', range: 'Painting System', hex: '#556eb1' },
  { brand: 'Citadel', ref: 'CALIBAN GREEN', name: '', range: 'Painting System', hex: '#153d23' },
  { brand: 'Citadel', ref: 'CASTELLAN GREEN', name: '', range: 'Painting System', hex: '#424e28' },
  { brand: 'Citadel', ref: 'CELESTRA GREY', name: '', range: 'Painting System', hex: '#a1adad' },
  { brand: 'Citadel', ref: 'CHANGELING PINK', name: '', range: 'Painting System', hex: '#e3b5d1' },
  { brand: 'Citadel', ref: 'CHRONUS BLUE', name: '', range: 'Painting System', hex: '#6e97cf' },
  { brand: 'Citadel', ref: 'DAWNSTONE', name: '', range: 'Painting System', hex: '#7b7c74' },
  { brand: 'Citadel', ref: 'DEATHCLAW BROWN', name: '', range: 'Painting System', hex: '#a66954' },
  { brand: 'Citadel', ref: 'DEATHWORLD FOREST', name: '', range: 'Painting System', hex: '#686d35' },
  { brand: 'Citadel', ref: 'DOOMBULL BROWN', name: '', range: 'Painting System', hex: '#520e0d' },
  { brand: 'Citadel', ref: 'DRYAD BARK', name: '', range: 'Painting System', hex: '#3c3733' },
  { brand: 'Citadel', ref: 'ELDAR FLESH', name: '', range: 'Painting System', hex: '#e3c386' },
  { brand: 'Citadel', ref: 'ELYSIAN GREEN', name: '', range: 'Painting System', hex: '#85923a' },
  { brand: 'Citadel', ref: 'EMPEROR\'S CHILDREN', name: '', range: 'Painting System', hex: '#a34172' },
  { brand: 'Citadel', ref: 'ESHIN GREY', name: '', range: 'Painting System', hex: '#565759' },
  { brand: 'Citadel', ref: 'EVIL SUNZ SCARLET', name: '', range: 'Painting System', hex: '#a31313' },
  { brand: 'Citadel', ref: 'FENRISIAN GREY', name: '', range: 'Painting System', hex: '#839db8' },
  { brand: 'Citadel', ref: 'FIRE DRAGON BRIGHT', name: '', range: 'Painting System', hex: '#d8824f' },
  { brand: 'Citadel', ref: 'FLASH GITZ YELLOW', name: '', range: 'Painting System', hex: '#feed01' },
  { brand: 'Citadel', ref: 'FLAYED ONE FLESH', name: '', range: 'Painting System', hex: '#e7c98b' },
  { brand: 'Citadel', ref: 'GENESTEALER PURPLE', name: '', range: 'Painting System', hex: '#735ca0' },
  { brand: 'Citadel', ref: 'GOLGFAG BROWN', name: '', range: 'Painting System', hex: '#8b5435' },
  { brand: 'Citadel', ref: 'GORTHOR BROWN', name: '', range: 'Painting System', hex: '#664f49' },
  { brand: 'Citadel', ref: 'HELLION GREEN', name: '', range: 'Painting System', hex: '#9fc2aa' },
  { brand: 'Citadel', ref: 'HEXOS PALESUN', name: '', range: 'Painting System', hex: '#feed01' },
  { brand: 'Citadel', ref: 'HOETH BLUE', name: '', range: 'Painting System', hex: '#607eb2' },
  { brand: 'Citadel', ref: 'IMRIK BLUE', name: '', range: 'Painting System', hex: '#4f8dbe' },
  { brand: 'Citadel', ref: 'INCUBI DARKNESS', name: '', range: 'Painting System', hex: '#294548' },
  { brand: 'Citadel', ref: 'JOKAERO ORANGE', name: '', range: 'Painting System', hex: '#c52517' },
  { brand: 'Citadel', ref: 'KABALITE GREEN', name: '', range: 'Painting System', hex: '#3e8563' },
  { brand: 'Citadel', ref: 'KANTOR BLUE', name: '', range: 'Painting System', hex: '#19284f' },
  { brand: 'Citadel', ref: 'KARAK STONE', name: '', range: 'Painting System', hex: '#b89e6b' },
  { brand: 'Citadel', ref: 'KHORNE RED', name: '', range: 'Painting System', hex: '#5b1104' },
  { brand: 'Citadel', ref: 'KINDLEFLAME', name: '', range: 'Painting System', hex: '#dfa18a' },
  { brand: 'Citadel', ref: 'KISLEV FLESH', name: '', range: 'Painting System', hex: '#cdac77' },
  { brand: 'Citadel', ref: 'LONGBEARD GREY', name: '', range: 'Painting System', hex: '#e5e2cf' },
  { brand: 'Citadel', ref: 'LOREN FOREST', name: '', range: 'Painting System', hex: '#647330' },
  { brand: 'Citadel', ref: 'LOTHERN BLUE', name: '', range: 'Painting System', hex: '#66a0ce' },
  { brand: 'Citadel', ref: 'LUCIUS LILAC', name: '', range: 'Painting System', hex: '#b8a6ce' },
  { brand: 'Citadel', ref: 'MACRAGGE BLUE', name: '', range: 'Painting System', hex: '#283c77' },
  { brand: 'Citadel', ref: 'MECHANICUS STANDARD GREY', name: '', range: 'Painting System', hex: '#494e51' },
  { brand: 'Citadel', ref: 'MEPHISTON RED', name: '', range: 'Painting System', hex: '#85160d' },
  { brand: 'Citadel', ref: 'MOOT GREEN', name: '', range: 'Painting System', hex: '#75a93b' },
  { brand: 'Citadel', ref: 'MOURNFANG BROWN', name: '', range: 'Painting System', hex: '#5a180a' },
  { brand: 'Citadel', ref: 'NAGGAROTH NIGHT', name: '', range: 'Painting System', hex: '#423956' },
  { brand: 'Citadel', ref: 'NIBLET GREEN', name: '', range: 'Painting System', hex: '#648a33' },
  { brand: 'Citadel', ref: 'NURGLING GREEN', name: '', range: 'Painting System', hex: '#95a064' },
  { brand: 'Citadel', ref: 'OGRYN CAMO', name: '', range: 'Painting System', hex: '#a9ad4c' },
  { brand: 'Citadel', ref: 'PALLID WYCH FLESH', name: '', range: 'Painting System', hex: '#d6d4c5' },
  { brand: 'Citadel', ref: 'PINK HORROR', name: '', range: 'Painting System', hex: '#81355b' },
  { brand: 'Citadel', ref: 'PRAXETI WHITE', name: '', range: 'Painting System', hex: '#ffffff' },
  { brand: 'Citadel', ref: 'RAKARTH FLESH', name: '', range: 'Painting System', hex: '#a9a395' },
  { brand: 'Citadel', ref: 'RHINOX HIDE', name: '', range: 'Painting System', hex: '#493735' },
  { brand: 'Citadel', ref: 'RUSS GREY', name: '', range: 'Painting System', hex: '#607588' },
  { brand: 'Citadel', ref: 'SCREAMER PINK', name: '', range: 'Painting System', hex: '#711d41' },
  { brand: 'Citadel', ref: 'SCREAMING SKULL', name: '', range: 'Painting System', hex: '#d8d7a7' },
  { brand: 'Citadel', ref: 'SKARSNIK GREEN', name: '', range: 'Painting System', hex: '#6f8f68' },
  { brand: 'Citadel', ref: 'SKAVENBLIGHT DINGE', name: '', range: 'Painting System', hex: '#4e4943' },
  { brand: 'Citadel', ref: 'SKINK BLUE', name: '', range: 'Painting System', hex: '#85bfcd' },
  { brand: 'Citadel', ref: 'SKRAG BROWN', name: '', range: 'Painting System', hex: '#844c13' },
  { brand: 'Citadel', ref: 'SOTEK GREEN', name: '', range: 'Painting System', hex: '#3d6976' },
  { brand: 'Citadel', ref: 'SQUIG ORANGE', name: '', range: 'Painting System', hex: '#9a4e41' },
  { brand: 'Citadel', ref: 'STEEL LEGION DRAB', name: '', range: 'Painting System', hex: '#645639' },
  { brand: 'Citadel', ref: 'STEGADON SCALE GREEN', name: '', range: 'Painting System', hex: '#254460' },
  { brand: 'Citadel', ref: 'STORMFANG', name: '', range: 'Painting System', hex: '#7188aa' },
  { brand: 'Citadel', ref: 'STORMVERMIN FUR', name: '', range: 'Painting System', hex: '#79726a' },
  { brand: 'Citadel', ref: 'STRAKEN GREEN', name: '', range: 'Painting System', hex: '#758425' },
  { brand: 'Citadel', ref: 'SYBARITE GREEN', name: '', range: 'Painting System', hex: '#649f65' },
  { brand: 'Citadel', ref: 'SYLVANETH BARK', name: '', range: 'Painting System', hex: '#5a5140' },
  { brand: 'Citadel', ref: 'TALLARN SAND', name: '', range: 'Painting System', hex: '#9e7c18' },
  { brand: 'Citadel', ref: 'TAU LIGHT OCHRE', name: '', range: 'Painting System', hex: '#af6e1c' },
  { brand: 'Citadel', ref: 'TECLIS BLUE', name: '', range: 'Painting System', hex: '#537abb' },
  { brand: 'Citadel', ref: 'TEMPLE GUARD BLUE', name: '', range: 'Painting System', hex: '#60988d' },
  { brand: 'Citadel', ref: 'TERMINATUS STONE', name: '', range: 'Painting System', hex: '#ccbb83' },
  { brand: 'Citadel', ref: 'THE FANG', name: '', range: 'Painting System', hex: '#567377' },
  { brand: 'Citadel', ref: 'TROLL SLAYER ORANGE', name: '', range: 'Painting System', hex: '#ce6426' },
  { brand: 'Citadel', ref: 'TUSKGOR FUR', name: '', range: 'Painting System', hex: '#7b3a36' },
  { brand: 'Citadel', ref: 'ULTHUAN GREY', name: '', range: 'Painting System', hex: '#d7e3df' },
  { brand: 'Citadel', ref: 'UNDERHIVE ASH', name: '', range: 'Painting System', hex: '#c5bf81' },
  { brand: 'Citadel', ref: 'UNGOR FLESH', name: '', range: 'Painting System', hex: '#ceab67' },
  { brand: 'Citadel', ref: 'USHABTI BONE', name: '', range: 'Painting System', hex: '#c4c083' },
  { brand: 'Citadel', ref: 'VERMINLORD HIDE', name: '', range: 'Painting System', hex: '#773a37' },
  { brand: 'Citadel', ref: 'WAAAGH FLESH', name: '', range: 'Painting System', hex: '#3c572e' },
  { brand: 'Citadel', ref: 'WARBOSS GREEN', name: '', range: 'Painting System', hex: '#567c57' },
  { brand: 'Citadel', ref: 'WARPSTONE GLOW', name: '', range: 'Painting System', hex: '#487230' },
  { brand: 'Citadel', ref: 'WAZDAKKA RED', name: '', range: 'Painting System', hex: '#791505' },
  { brand: 'Citadel', ref: 'WHITE SCAR', name: '', range: 'Painting System', hex: '#ffffff' },
  { brand: 'Citadel', ref: 'WILD RIDER RED', name: '', range: 'Painting System', hex: '#c21c1c' },
  { brand: 'Citadel', ref: 'WRACK WHITE', name: '', range: 'Painting System', hex: '#dedad9' },
  { brand: 'Citadel', ref: 'XEREUS PURPLE', name: '', range: 'Painting System', hex: '#43255b' },
  { brand: 'Citadel', ref: 'XV-88', name: '', range: 'Painting System', hex: '#704f26' },
  { brand: 'Citadel', ref: 'YRIEL YELLOW', name: '', range: 'Painting System', hex: '#f7d900' },
  { brand: 'Citadel', ref: 'ZAMESI DESERT', name: '', range: 'Painting System', hex: '#d0a326' },
  { brand: 'Citadel', ref: 'ZANDRI DUST', name: '', range: 'Painting System', hex: '#a2965c' },
]
