/**
 * Pro Acryl paint catalogue, extracted from Set List.pdf (Monument Hobbies).
 *
 * GENERATED — do not hand-edit. Regenerate with `scripts/extract-proacryl.py` followed by
 * `scripts/generate-catalogue.py`; those files document the page formats they read, the
 * exclusions they apply, and how the colours are obtained.
 *
 * Committed rather than built, because it is derived once from a PDF the repository does
 * not contain. It is source data for the app, not a build artefact.
 *
 * WHAT THESE COLOURS ARE, precisely: the swatch colours printed in the catalogue. They
 * are the manufacturer's own print renderings, not spectrophotometer readings of dried
 * paint. Good enough to say "this bottle is in the right area", not good enough to treat
 * as colorimetric truth — see D40 and D44 in the spec, and the caveat the UI shows.
 */

import type { Paint } from './types.ts'

export const PRO_ACRYL_PAINTS: readonly Paint[] = [

  { brand: 'Pro Acryl', ref: 'AMP-002', name: 'Cool Grey', range: 'AMP Colors Set #1', hex: '#797c79' },
  { brand: 'Pro Acryl', ref: 'AMP-004', name: 'Black Red', range: 'AMP Colors Set #1', hex: '#522b28' },
  { brand: 'Pro Acryl', ref: 'AMP-005', name: 'Dark Navy Blue', range: 'AMP Colors Set #1', hex: '#1d1f2d' },
  { brand: 'Pro Acryl', ref: 'AMP-006', name: 'Beige Grey', range: 'AMP Colors Set #1', hex: '#947259' },
  { brand: 'Pro Acryl', ref: 'AMP-007', name: 'Orange Yellow', range: 'AMP Colors Set #1', hex: '#ea9335' },
  { brand: 'Pro Acryl', ref: 'AMP-008', name: 'Peach Flesh', range: 'AMP Colors Set #1', hex: '#edb389' },
  { brand: 'Pro Acryl', ref: 'AMP-009', name: 'Bright Green Blue', range: 'AMP Colors Set #1', hex: '#8c9d94' },
  { brand: 'Pro Acryl', ref: 'AMP-013', name: 'Slate Grey', range: 'AMP Colors Set #2', hex: '#3f3f42' },
  { brand: 'Pro Acryl', ref: 'AMP-017', name: 'Red Orange', range: 'AMP Colors Set #2', hex: '#db422b' },
  { brand: 'Pro Acryl', ref: 'AMP-018', name: 'Burnt Umber', range: 'AMP Colors Set #2', hex: '#704435' },
  { brand: 'Pro Acryl', ref: 'AMP-020', name: 'Green Brown', range: 'AMP Colors Set #2', hex: '#84634a' },
  { brand: 'Pro Acryl', ref: 'AMP-021', name: 'Bright Brown Grey', range: 'AMP Colors Set #2', hex: '#837364' },
  { brand: 'Pro Acryl', ref: 'AMP-022', name: 'Grey Green', range: 'AMP Colors Set #2', hex: '#5b554a' },
  { brand: 'Pro Acryl', ref: 'S37', name: 'Red Oxide', range: 'AdeptiCon Spray-Team Set', hex: '#863531' },
  { brand: 'Pro Acryl', ref: 'S38', name: 'Orange Oxide', range: 'AdeptiCon Spray-Team Set', hex: '#814c31' },
  { brand: 'Pro Acryl', ref: 'S39', name: 'Satin Black', range: 'AdeptiCon Spray-Team Set', hex: '#131212' },
  { brand: 'Pro Acryl', ref: 'S40', name: 'Drab Brown', range: 'AdeptiCon Spray-Team Set', hex: '#4e3e28' },
  { brand: 'Pro Acryl', ref: 'S41', name: 'Bright Shadow Flesh', range: 'AdeptiCon Spray-Team Set', hex: '#f79b7d' },
  { brand: 'Pro Acryl', ref: '001', name: 'Bold Titanium White', range: 'Base Set', hex: '#ffffff' },
  { brand: 'Pro Acryl', ref: '002', name: 'Coal Black', range: 'Base Set', hex: '#262626' },
  { brand: 'Pro Acryl', ref: '003', name: 'Bold Pyrrole Red', range: 'Base Set', hex: '#ce2030' },
  { brand: 'Pro Acryl', ref: '004', name: 'Green', range: 'Base Set', hex: '#008348' },
  { brand: 'Pro Acryl', ref: '005', name: 'Blue', range: 'Base Set', hex: '#0a5fad' },
  { brand: 'Pro Acryl', ref: '006', name: 'Golden Yellow', range: 'Base Set', hex: '#fcd701' },
  { brand: 'Pro Acryl', ref: '007', name: 'Orange', range: 'Base Set', hex: '#f47929' },
  { brand: 'Pro Acryl', ref: '008', name: 'Burnt Red', range: 'Base Set', hex: '#803536' },
  { brand: 'Pro Acryl', ref: '009', name: 'Mahogany', range: 'Base Set', hex: '#4e3c39' },
  { brand: 'Pro Acryl', ref: '010', name: 'Purple', range: 'Base Set', hex: '#7e4f7c' },
  { brand: 'Pro Acryl', ref: '011', name: 'Magenta', range: 'Base Set', hex: '#be4a72' },
  { brand: 'Pro Acryl', ref: '012', name: 'Sky Blue', range: 'Base Set', hex: '#30a0da' },
  { brand: 'Pro Acryl', ref: '013', name: 'Faded Ultramarine', range: 'Base Set', hex: '#6489c6' },
  { brand: 'Pro Acryl', ref: '014', name: 'Dark Grey Blue', range: 'Base Set', hex: '#183b60' },
  { brand: 'Pro Acryl', ref: '015', name: 'Bright Warm Grey', range: 'Base Set', hex: '#adb4a2' },
  { brand: 'Pro Acryl', ref: '016', name: 'Dark Warm Grey', range: 'Base Set', hex: '#4c4e51' },
  { brand: 'Pro Acryl', ref: '017', name: 'Golden Brown', range: 'Base Set', hex: '#d5ae6d' },
  { brand: 'Pro Acryl', ref: '018', name: 'Light Umber', range: 'Base Set', hex: '#6f5548' },
  { brand: 'Pro Acryl', ref: '019', name: 'Dark Umber', range: 'Base Set', hex: '#52423c' },
  { brand: 'Pro Acryl', ref: '020', name: 'Camo Green', range: 'Base Set', hex: '#515f4a' },
  { brand: 'Pro Acryl', ref: '021', name: 'Jade', range: 'Base Set', hex: '#016161' },
  { brand: 'Pro Acryl', ref: '022', name: 'Bright Ivory', range: 'Base Set', hex: '#faf6e1' },
  { brand: 'Pro Acryl', ref: '023', name: 'Ivory', range: 'Base Set', hex: '#e5dbcb' },
  { brand: 'Pro Acryl', ref: '024', name: 'Tan Flesh', range: 'Base Set', hex: '#e0b5a5' },
  { brand: 'Pro Acryl', ref: '034', name: 'Dark Blue', range: 'Expansion Set #1', hex: '#141f46' },
  { brand: 'Pro Acryl', ref: '035', name: 'Dark Purple', range: 'Expansion Set #1', hex: '#221e4a' },
  { brand: 'Pro Acryl', ref: '036', name: 'Dark Camo Green', range: 'Expansion Set #1', hex: '#4f5348' },
  { brand: 'Pro Acryl', ref: '037', name: 'Burnt Orange', range: 'Expansion Set #1', hex: '#9d473a' },
  { brand: 'Pro Acryl', ref: '038', name: 'Yellow Ochre', range: 'Expansion Set #1', hex: '#ce9a49' },
  { brand: 'Pro Acryl', ref: '039', name: 'Bright Yellow Green', range: 'Expansion Set #1', hex: '#96bb3d' },
  { brand: 'Pro Acryl', ref: '040', name: 'Black Brown', range: 'Expansion Set #1', hex: '#474241' },
  { brand: 'Pro Acryl', ref: '041', name: 'Olive Flesh', range: 'Expansion Set #1', hex: '#c6b49d' },
  { brand: 'Pro Acryl', ref: '042', name: 'Shadow Flesh', range: 'Expansion Set #1', hex: '#a06159' },
  { brand: 'Pro Acryl', ref: '043', name: 'Pale Pink', range: 'Expansion Set #1', hex: '#f9d8d5' },
  { brand: 'Pro Acryl', ref: '044', name: 'Dark Neutral Grey', range: 'Expansion Set #1', hex: '#434549' },
  { brand: 'Pro Acryl', ref: '045', name: 'Bright Neutral Grey', range: 'Expansion Set #1', hex: '#dad9d9' },
  { brand: 'Pro Acryl', ref: '054', name: 'Turquoise', range: 'Expansion Set #3', hex: '#00a1b3' },
  { brand: 'Pro Acryl', ref: '055', name: 'Grey Blue', range: 'Expansion Set #3', hex: '#80a2c0' },
  { brand: 'Pro Acryl', ref: '056', name: 'Blue Black', range: 'Expansion Set #3', hex: '#41474f' },
  { brand: 'Pro Acryl', ref: '057', name: 'Black Green', range: 'Expansion Set #3', hex: '#38413b' },
  { brand: 'Pro Acryl', ref: '058', name: 'Bright Pale Green', range: 'Expansion Set #3', hex: '#bbddcd' },
  { brand: 'Pro Acryl', ref: '059', name: 'Burnt Sienna', range: 'Expansion Set #3', hex: '#743424' },
  { brand: 'Pro Acryl', ref: '060', name: 'Pale Yellow', range: 'Expansion Set #3', hex: '#ffefb1' },
  { brand: 'Pro Acryl', ref: '062', name: 'Dark Golden Brown', range: 'Expansion Set #3', hex: '#5f481c' },
  { brand: 'Pro Acryl', ref: '063', name: 'Faded Plum', range: 'Expansion Set #3', hex: '#a08cb5' },
  { brand: 'Pro Acryl', ref: '061', name: 'Khaki', range: 'Expansion Set #4', hex: '#d2c59c' },
  { brand: 'Pro Acryl', ref: '065', name: 'Yellow Green', range: 'Expansion Set #4', hex: '#6d7645' },
  { brand: 'Pro Acryl', ref: '066', name: 'Faded Green', range: 'Expansion Set #4', hex: '#97a88f' },
  { brand: 'Pro Acryl', ref: '067', name: 'Bright Jade', range: 'Expansion Set #4', hex: '#3c9f8b' },
  { brand: 'Pro Acryl', ref: '068', name: 'Dark Flesh', range: 'Expansion Set #4', hex: '#603c39' },
  { brand: 'Pro Acryl', ref: '069', name: 'Burgundy', range: 'Expansion Set #4', hex: '#76303b' },
  { brand: 'Pro Acryl', ref: '070', name: 'Plum', range: 'Expansion Set #4', hex: '#8a4f8b' },
  { brand: 'Pro Acryl', ref: '071', name: 'Pink', range: 'Expansion Set #4', hex: '#f09fad' },
  { brand: 'Pro Acryl', ref: '072', name: 'Warm Yellow', range: 'Expansion Set #4', hex: '#fdc110' },
  { brand: 'Pro Acryl', ref: '073', name: 'Warm Flesh', range: 'Expansion Set #4', hex: '#feca85' },
  { brand: 'Pro Acryl', ref: '074', name: 'Warm Grey', range: 'Expansion Set #4', hex: '#616769' },
  { brand: 'Pro Acryl', ref: '075', name: 'Neutral Grey', range: 'Expansion Set #4', hex: '#585f66' },
  { brand: 'Pro Acryl', ref: 'E001', name: 'Titanium White', range: 'Expert Artist Acrylics Series #1', hex: '#fffffe' },
  { brand: 'Pro Acryl', ref: 'E002', name: 'Carbon Black', range: 'Expert Artist Acrylics Series #1', hex: '#20211f' },
  { brand: 'Pro Acryl', ref: 'E003', name: 'Pyrrole Red', range: 'Expert Artist Acrylics Series #1', hex: '#db3a35' },
  { brand: 'Pro Acryl', ref: 'E004', name: 'Permanent Green Light', range: 'Expert Artist Acrylics Series #1', hex: '#117a46' },
  { brand: 'Pro Acryl', ref: 'E005', name: 'Prussian Blue', range: 'Expert Artist Acrylics Series #1', hex: '#222250' },
  { brand: 'Pro Acryl', ref: 'E006', name: 'Pyrrole Orange', range: 'Expert Artist Acrylics Series #1', hex: '#dd492a' },
  { brand: 'Pro Acryl', ref: 'E007', name: 'Burnt Umber', range: 'Expert Artist Acrylics Series #1', hex: '#3d2e26' },
  { brand: 'Pro Acryl', ref: 'E008', name: 'Dioxazine Violet', range: 'Expert Artist Acrylics Series #1', hex: '#2a193a' },
  { brand: 'Pro Acryl', ref: 'E009', name: 'Sap Green', range: 'Expert Artist Acrylics Series #1', hex: '#123e2a' },
  { brand: 'Pro Acryl', ref: 'E010', name: 'Burnt Sienna', range: 'Expert Artist Acrylics Series #1', hex: '#673125' },
  { brand: 'Pro Acryl', ref: 'E011', name: 'Nickel Azo Yellow', range: 'Expert Artist Acrylics Series #1', hex: '#986334' },
  { brand: 'Pro Acryl', ref: 'E012', name: 'Sepia', range: 'Expert Artist Acrylics Series #1', hex: '#302519' },
  { brand: 'Pro Acryl', ref: 'E013', name: 'Payne’s Grey', range: 'Expert Artist Acrylics Series #1', hex: '#1e262e' },
  { brand: 'Pro Acryl', ref: 'E014', name: 'Primary Cyan', range: 'Expert Artist Acrylics Series #1', hex: '#2f377f' },
  { brand: 'Pro Acryl', ref: 'E015', name: 'Primary Magenta', range: 'Expert Artist Acrylics Series #1', hex: '#ac263a' },
  { brand: 'Pro Acryl', ref: 'E016', name: 'Primary Yellow', range: 'Expert Artist Acrylics Series #1', hex: '#f4bb28' },
  { brand: 'Pro Acryl', ref: 'E017', name: 'Chrome Oxide Green', range: 'Expert Artist Acrylics Series #2', hex: '#558a42' },
  { brand: 'Pro Acryl', ref: 'E018', name: 'Red Oxide Tint', range: 'Expert Artist Acrylics Series #2', hex: '#ca9f80' },
  { brand: 'Pro Acryl', ref: 'E019', name: 'Pthalo Turquoise Light', range: 'Expert Artist Acrylics Series #2', hex: '#5b8691' },
  { brand: 'Pro Acryl', ref: 'E020', name: 'Quinacridone Magenta', range: 'Expert Artist Acrylics Series #2', hex: '#902b5f' },
  { brand: 'Pro Acryl', ref: 'E021', name: 'Arylide Yellow Deep', range: 'Expert Artist Acrylics Series #2', hex: '#f4b628' },
  { brand: 'Pro Acryl', ref: 'E022', name: 'Alizarin Crimson Hue', range: 'Expert Artist Acrylics Series #2', hex: '#823434' },
  { brand: 'Pro Acryl', ref: 'F01', name: 'Fluorescent Red', range: 'Fluorescent Set', hex: '#ef3a37' },
  { brand: 'Pro Acryl', ref: 'F02', name: 'Fluorescent Orange', range: 'Fluorescent Set', hex: '#f04d26' },
  { brand: 'Pro Acryl', ref: 'F03', name: 'Fluorescent Yellow', range: 'Fluorescent Set', hex: '#f2dd26' },
  { brand: 'Pro Acryl', ref: 'F04', name: 'Fluorescent Green', range: 'Fluorescent Set', hex: '#3fb549' },
  { brand: 'Pro Acryl', ref: 'F05', name: 'Fluorescent Purple', range: 'Fluorescent Set', hex: '#a32388' },
  { brand: 'Pro Acryl', ref: 'F06', name: 'Fluorescent Pink', range: 'Fluorescent Set', hex: '#ee387c' },
  { brand: 'Pro Acryl', ref: 'S01', name: 'Dark Jade', range: 'Signature Set #1 - Vince Venturella', hex: '#2c454c' },
  { brand: 'Pro Acryl', ref: 'S02', name: 'Payne’s Grey', range: 'Signature Set #1 - Vince Venturella', hex: '#333a52' },
  { brand: 'Pro Acryl', ref: 'S03', name: 'Royal Purple', range: 'Signature Set #1 - Vince Venturella', hex: '#513660' },
  { brand: 'Pro Acryl', ref: 'S04', name: 'White Blue', range: 'Signature Set #1 - Vince Venturella', hex: '#c4e7ec' },
  { brand: 'Pro Acryl', ref: 'S05', name: 'Beige Red', range: 'Signature Set #1 - Vince Venturella', hex: '#af837b' },
  { brand: 'Pro Acryl', ref: 'S06', name: 'Dark Yellow Green', range: 'Signature Set #1 - Vince Venturella', hex: '#55583e' },
  { brand: 'Pro Acryl', ref: 'S07', name: 'Dark Ivory', range: 'Signature Set #2 - Ninjon', hex: '#bcbaac' },
  { brand: 'Pro Acryl', ref: 'S08', name: 'Dark Warm Flesh', range: 'Signature Set #2 - Ninjon', hex: '#e0b06f' },
  { brand: 'Pro Acryl', ref: 'S09', name: 'Warm Brown', range: 'Signature Set #2 - Ninjon', hex: '#895141' },
  { brand: 'Pro Acryl', ref: 'S10', name: 'Dark Magenta', range: 'Signature Set #2 - Ninjon', hex: '#821431' },
  { brand: 'Pro Acryl', ref: 'S11', name: 'Dark Plum', range: 'Signature Set #2 - Ninjon', hex: '#43222d' },
  { brand: 'Pro Acryl', ref: 'S12', name: 'Red Grey', range: 'Signature Set #2 - Ninjon', hex: '#715d60' },
  { brand: 'Pro Acryl', ref: 'S13', name: 'Dark Sea Ben', range: 'Signature Set #3 - Ben Komets', hex: '#002636' },
  { brand: 'Pro Acryl', ref: 'S14', name: 'Petroleum Brown', range: 'Signature Set #3 - Ben Komets', hex: '#462a17' },
  { brand: 'Pro Acryl', ref: 'S15', name: 'Dark Burgguunnddy', range: 'Signature Set #3 - Ben Komets', hex: '#351e1e' },
  { brand: 'Pro Acryl', ref: 'S16', name: 'Green Oxide', range: 'Signature Set #3 - Ben Komets', hex: '#006d60' },
  { brand: 'Pro Acryl', ref: 'S17', name: 'Advanced Flesh Tone', range: 'Signature Set #3 - Ben Komets', hex: '#9b6653' },
  { brand: 'Pro Acryl', ref: 'S18', name: 'Heavy Warm White', range: 'Signature Set #3 - Ben Komets', hex: '#ffdfae' },
  { brand: 'Pro Acryl', ref: 'S19', name: 'Dark Crimson', range: 'Signature Set #4 - Matt Cexwish', hex: '#441916' },
  { brand: 'Pro Acryl', ref: 'S20', name: 'Dark Emerald', range: 'Signature Set #4 - Matt Cexwish', hex: '#14494d' },
  { brand: 'Pro Acryl', ref: 'S21', name: 'Heavy Titanium White', range: 'Signature Set #4 - Matt Cexwish', hex: '#ffffff' },
  { brand: 'Pro Acryl', ref: 'S22', name: 'Brown Grey', range: 'Signature Set #4 - Matt Cexwish', hex: '#53514e' },
  { brand: 'Pro Acryl', ref: 'S23', name: 'Bone', range: 'Signature Set #4 - Matt Cexwish', hex: '#a2978f' },
  { brand: 'Pro Acryl', ref: 'S25', name: 'Dark Green Brown', range: 'Signature Set #5 - Flameon', hex: '#3f311f' },
  { brand: 'Pro Acryl', ref: 'S26', name: 'Dark Orange Brown', range: 'Signature Set #5 - Flameon', hex: '#614529' },
  { brand: 'Pro Acryl', ref: 'S27', name: 'Orange Brown', range: 'Signature Set #5 - Flameon', hex: '#8d5c25' },
  { brand: 'Pro Acryl', ref: 'S28', name: 'Caramel Brown', range: 'Signature Set #5 - Flameon', hex: '#805f3e' },
  { brand: 'Pro Acryl', ref: 'S29', name: 'Bright Yellow Ochre', range: 'Signature Set #5 - Flameon', hex: '#dda55b' },
  { brand: 'Pro Acryl', ref: 'S30', name: 'Bright Pale Yellow', range: 'Signature Set #5 - Flameon', hex: '#fff7cd' },
  { brand: 'Pro Acryl', ref: 'S31', name: 'Orange Red', range: 'Signature Set #6 - Rogue Hobbies', hex: '#e53941' },
  { brand: 'Pro Acryl', ref: 'S32', name: 'Dark Hot Pink', range: 'Signature Set #6 - Rogue Hobbies', hex: '#c32c5b' },
  { brand: 'Pro Acryl', ref: 'S33', name: 'Bright Green', range: 'Signature Set #6 - Rogue Hobbies', hex: '#12a361' },
  { brand: 'Pro Acryl', ref: 'S34', name: 'Dark Turquoise', range: 'Signature Set #6 - Rogue Hobbies', hex: '#167d94' },
  { brand: 'Pro Acryl', ref: 'S35', name: 'Ultramarine', range: 'Signature Set #6 - Rogue Hobbies', hex: '#3d5eab' },
  { brand: 'Pro Acryl', ref: 'S36', name: 'Bismuth Yellow', range: 'Signature Set #6 - Rogue Hobbies', hex: '#f9d967' },
]
