/**
 * Vallejo paint catalogue, extracted from Catalogo_2026-R02.pdf (Vallejo).
 *
 * GENERATED — do not hand-edit. Regenerate with `scripts/extract-vallejo.py` followed by
 * `scripts/generate-catalogue.py`; those files document the page formats they read, the
 * exclusions they apply, and how the colours are obtained.
 *
 * Committed rather than built, because it is derived once from a PDF the repository does
 * not contain. It is source data for the app, not a build artefact.
 *
 * WHAT THESE COLOURS ARE, precisely: the swatch colours printed in the catalogue. They
 * are the manufacturer's own print renderings, not spectrophotometer readings of dried
 * paint. Good enough to say "this bottle is in the right area", not good enough to treat
 * as colorimetric truth — see D40 and D44 in the spec, and the caveat the UI shows.
 */

import type { Paint } from './types.ts'

export const VALLEJO_PAINTS: readonly Paint[] = [

  { brand: 'Vallejo', ref: '76.001', name: 'Dead White', range: 'Game Air', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '76.003', name: 'Pale Flesh', range: 'Game Air', hex: '#e1a17b' },
  { brand: 'Vallejo', ref: '76.004', name: 'Elf Skin Tone', range: 'Game Air', hex: '#d68849' },
  { brand: 'Vallejo', ref: '76.005', name: 'Moon Yellow', range: 'Game Air', hex: '#eea200' },
  { brand: 'Vallejo', ref: '76.006', name: 'Sun Yellow', range: 'Game Air', hex: '#f49600' },
  { brand: 'Vallejo', ref: '76.007', name: 'Gold Yellow', range: 'Game Air', hex: '#ed7004' },
  { brand: 'Vallejo', ref: '76.008', name: 'Orange Fire', range: 'Game Air', hex: '#e84b0f' },
  { brand: 'Vallejo', ref: '76.010', name: 'Bloody Red', range: 'Game Air', hex: '#9e1e14' },
  { brand: 'Vallejo', ref: '76.012', name: 'Scarlet Red', range: 'Game Air', hex: '#3f120f' },
  { brand: 'Vallejo', ref: '76.013', name: 'Squid Pink', range: 'Game Air', hex: '#b75f99' },
  { brand: 'Vallejo', ref: '76.014', name: 'Warlord Purple', range: 'Game Air', hex: '#5d1738' },
  { brand: 'Vallejo', ref: '76.016', name: 'Royal Purple', range: 'Game Air', hex: '#291d34' },
  { brand: 'Vallejo', ref: '76.019', name: 'Night Blue', range: 'Game Air', hex: '#1d1a24' },
  { brand: 'Vallejo', ref: '76.020', name: 'Imperial Blue', range: 'Game Air', hex: '#191b30' },
  { brand: 'Vallejo', ref: '76.021', name: 'Magic Blue', range: 'Game Air', hex: '#1c3f88' },
  { brand: 'Vallejo', ref: '76.022', name: 'Ultramarine Blue', range: 'Game Air', hex: '#232341' },
  { brand: 'Vallejo', ref: '76.023', name: 'Electric Blue', range: 'Game Air', hex: '#337ca4' },
  { brand: 'Vallejo', ref: '76.024', name: 'Turquoise', range: 'Game Air', hex: '#004a52' },
  { brand: 'Vallejo', ref: '76.026', name: 'Jade Green', range: 'Game Air', hex: '#00654d' },
  { brand: 'Vallejo', ref: '76.027', name: 'Scurvy Green', range: 'Game Air', hex: '#183b33' },
  { brand: 'Vallejo', ref: '76.028', name: 'Dark Green', range: 'Game Air', hex: '#252d22' },
  { brand: 'Vallejo', ref: '76.031', name: 'Camouflage Green', range: 'Game Air', hex: '#796a2d' },
  { brand: 'Vallejo', ref: '76.032', name: 'Scorpy Green', range: 'Game Air', hex: '#537b35' },
  { brand: 'Vallejo', ref: '76.034', name: 'Bone White', range: 'Game Air', hex: '#af976b' },
  { brand: 'Vallejo', ref: '76.035', name: 'Dead Flesh', range: 'Game Air', hex: '#a58d46' },
  { brand: 'Vallejo', ref: '76.036', name: 'Bronze Brown', range: 'Game Air', hex: '#b16821' },
  { brand: 'Vallejo', ref: '76.040', name: 'Leather Brown', range: 'Game Air', hex: '#5f3d19' },
  { brand: 'Vallejo', ref: '76.042', name: 'Parasite Brown', range: 'Game Air', hex: '#67370d' },
  { brand: 'Vallejo', ref: '76.043', name: 'Beasty Brown', range: 'Game Air', hex: '#492e0c' },
  { brand: 'Vallejo', ref: '76.045', name: 'Charred Brown', range: 'Game Air', hex: '#2e1c10' },
  { brand: 'Vallejo', ref: '76.047', name: 'Wolf Grey', range: 'Game Air', hex: '#a7babe' },
  { brand: 'Vallejo', ref: '76.048', name: 'Sombre Grey', range: 'Game Air', hex: '#363d43' },
  { brand: 'Vallejo', ref: '76.049', name: 'Stonewall Grey', range: 'Game Air', hex: '#726d65' },
  { brand: 'Vallejo', ref: '76.050', name: 'Neutral Grey', range: 'Game Air', hex: '#474747' },
  { brand: 'Vallejo', ref: '76.051', name: 'Black', range: 'Game Air', hex: '#000000' },
  { brand: 'Vallejo', ref: '76.062', name: 'Earth', range: 'Game Air', hex: '#423118' },
  { brand: 'Vallejo', ref: '76.063', name: 'Desert Yellow', range: 'Game Air', hex: '#7d5d2a' },
  { brand: 'Vallejo', ref: '76.071', name: 'Barbarian Skin', range: 'Game Air', hex: '#7b5c38' },
  { brand: 'Vallejo', ref: '76.076', name: 'Alien Purple', range: 'Game Air', hex: '#55417c' },
  { brand: 'Vallejo', ref: '76.100', name: 'Rosy Flesh', range: 'Game Air', hex: '#e16f59' },
  { brand: 'Vallejo', ref: '76.107', name: 'Athena Skin', range: 'Game Air', hex: '#af5444' },
  { brand: 'Vallejo', ref: '76.109', name: 'Toxic Yellow', range: 'Game Air', hex: '#edc434' },
  { brand: 'Vallejo', ref: '76.111', name: 'Nocturnal Red', range: 'Game Air', hex: '#2d1211' },
  { brand: 'Vallejo', ref: '76.114', name: 'Lustful Purple', range: 'Game Air', hex: '#8966a8' },
  { brand: 'Vallejo', ref: '76.115', name: 'Grunge Brown', range: 'Game Air', hex: '#633625' },
  { brand: 'Vallejo', ref: '76.116', name: 'Midnight Purple', range: 'Game Air', hex: '#170b18' },
  { brand: 'Vallejo', ref: '76.118', name: 'Sunrise Blue', range: 'Game Air', hex: '#52b0d4' },
  { brand: 'Vallejo', ref: '76.120', name: 'Abyssal Turquoise', range: 'Game Air', hex: '#162731' },
  { brand: 'Vallejo', ref: '76.121', name: 'Ghost Green', range: 'Game Air', hex: '#55b484' },
  { brand: 'Vallejo', ref: '76.122', name: 'Bile Green', range: 'Game Air', hex: '#d5d900' },
  { brand: 'Vallejo', ref: '76.123', name: 'Angel Green', range: 'Game Air', hex: '#222c1b' },
  { brand: 'Vallejo', ref: '72.001', name: 'Dead White', range: 'Game Color', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '72.003', name: 'Pale Flesh', range: 'Game Color', hex: '#ce9a7a' },
  { brand: 'Vallejo', ref: '72.004', name: 'Elf Skin Tone', range: 'Game Color', hex: '#c47e52' },
  { brand: 'Vallejo', ref: '72.005', name: 'Moon Yellow', range: 'Game Color', hex: '#efb800' },
  { brand: 'Vallejo', ref: '72.006', name: 'Sun Yellow', range: 'Game Color', hex: '#f49405' },
  { brand: 'Vallejo', ref: '72.007', name: 'Gold Yellow', range: 'Game Color', hex: '#e77712' },
  { brand: 'Vallejo', ref: '72.008', name: 'Orange Fire', range: 'Game Color', hex: '#e9531d' },
  { brand: 'Vallejo', ref: '72.009', name: 'Hot Orange', range: 'Game Color', hex: '#d8311d' },
  { brand: 'Vallejo', ref: '72.010', name: 'Bloody Red', range: 'Game Color', hex: '#d41d1b' },
  { brand: 'Vallejo', ref: '72.011', name: 'Gory Red', range: 'Game Color', hex: '#611715' },
  { brand: 'Vallejo', ref: '72.012', name: 'Scarlet Red', range: 'Game Color', hex: '#581a22' },
  { brand: 'Vallejo', ref: '72.013', name: 'Squid Pink', range: 'Game Color', hex: '#cb6f9e' },
  { brand: 'Vallejo', ref: '72.014', name: 'Warlord Purple', range: 'Game Color', hex: '#7e223e' },
  { brand: 'Vallejo', ref: '72.015', name: 'Hexed Lichen', range: 'Game Color', hex: '#351939' },
  { brand: 'Vallejo', ref: '72.016', name: 'Royal Purple', range: 'Game Color', hex: '#251930' },
  { brand: 'Vallejo', ref: '72.019', name: 'Night Blue', range: 'Game Color', hex: '#0f0f1c' },
  { brand: 'Vallejo', ref: '72.020', name: 'Imperial Blue', range: 'Game Color', hex: '#132032' },
  { brand: 'Vallejo', ref: '72.021', name: 'Magic Blue', range: 'Game Color', hex: '#133d7d' },
  { brand: 'Vallejo', ref: '72.022', name: 'Ultramarine Blue', range: 'Game Color', hex: '#1b224b' },
  { brand: 'Vallejo', ref: '72.023', name: 'Electric Blue', range: 'Game Color', hex: '#006c88' },
  { brand: 'Vallejo', ref: '72.024', name: 'Turquoise', range: 'Game Color', hex: '#004145' },
  { brand: 'Vallejo', ref: '72.025', name: 'Foul Green', range: 'Game Color', hex: '#156d53' },
  { brand: 'Vallejo', ref: '72.026', name: 'Jade Green', range: 'Game Color', hex: '#004938' },
  { brand: 'Vallejo', ref: '72.027', name: 'Scurvy Green', range: 'Game Color', hex: '#003426' },
  { brand: 'Vallejo', ref: '72.028', name: 'Dark Green', range: 'Game Color', hex: '#122418' },
  { brand: 'Vallejo', ref: '72.029', name: 'Sick Green', range: 'Game Color', hex: '#3b5b33' },
  { brand: 'Vallejo', ref: '72.030', name: 'Goblin Green', range: 'Game Color', hex: '#43502a' },
  { brand: 'Vallejo', ref: '72.031', name: 'Camouflage Green', range: 'Game Color', hex: '#6e6128' },
  { brand: 'Vallejo', ref: '72.032', name: 'Scorpy Green', range: 'Game Color', hex: '#427a33' },
  { brand: 'Vallejo', ref: '72.034', name: 'Bone White', range: 'Game Color', hex: '#b49b6d' },
  { brand: 'Vallejo', ref: '72.035', name: 'Dead Flesh', range: 'Game Color', hex: '#937f3a' },
  { brand: 'Vallejo', ref: '72.036', name: 'Bronze Brown', range: 'Game Color', hex: '#985b1b' },
  { brand: 'Vallejo', ref: '72.038', name: 'Scrofulous Brown', range: 'Game Color', hex: '#a85e17' },
  { brand: 'Vallejo', ref: '72.039', name: 'Plague Brown', range: 'Game Color', hex: '#8f5e24' },
  { brand: 'Vallejo', ref: '72.040', name: 'Leather Brown', range: 'Game Color', hex: '#4f3413' },
  { brand: 'Vallejo', ref: '72.042', name: 'Parasite Brown', range: 'Game Color', hex: '#6f3c1a' },
  { brand: 'Vallejo', ref: '72.043', name: 'Beasty Brown', range: 'Game Color', hex: '#55381d' },
  { brand: 'Vallejo', ref: '72.044', name: 'Dark Flesh Tone', range: 'Game Color', hex: '#411f15' },
  { brand: 'Vallejo', ref: '72.045', name: 'Charred Brown', range: 'Game Color', hex: '#281a14' },
  { brand: 'Vallejo', ref: '72.047', name: 'Wolf Grey', range: 'Game Color', hex: '#95b4bb' },
  { brand: 'Vallejo', ref: '72.048', name: 'Sombre Grey', range: 'Game Color', hex: '#373e45' },
  { brand: 'Vallejo', ref: '72.049', name: 'Stonewall Grey', range: 'Game Color', hex: '#615e5b' },
  { brand: 'Vallejo', ref: '72.050', name: 'Neutral Grey', range: 'Game Color', hex: '#484744' },
  { brand: 'Vallejo', ref: '72.051', name: 'Black', range: 'Game Color', hex: '#000000' },
  { brand: 'Vallejo', ref: '72.052', name: 'Silver', range: 'Game Color', hex: '#f4f5f5' },
  { brand: 'Vallejo', ref: '72.053', name: 'Chainmail', range: 'Game Color', hex: '#eeeff0' },
  { brand: 'Vallejo', ref: '72.054', name: 'Dark Gunmetal', range: 'Game Color', hex: '#e8e8e9' },
  { brand: 'Vallejo', ref: '72.055', name: 'Polished Gold', range: 'Game Color', hex: '#fbf3db' },
  { brand: 'Vallejo', ref: '72.056', name: 'Glorious Gold', range: 'Game Color', hex: '#f9eee0' },
  { brand: 'Vallejo', ref: '72.057', name: 'Bright Bronze', range: 'Game Color', hex: '#f2e7dc' },
  { brand: 'Vallejo', ref: '72.058', name: 'Brassy Brass', range: 'Game Color', hex: '#f2e6df' },
  { brand: 'Vallejo', ref: '72.059', name: 'Hammered Copper', range: 'Game Color', hex: '#ebe5e1' },
  { brand: 'Vallejo', ref: '72.060', name: 'Tinny Tin', range: 'Game Color', hex: '#e6e1dd' },
  { brand: 'Vallejo', ref: '72.061', name: 'Khaki', range: 'Game Color', hex: '#776247' },
  { brand: 'Vallejo', ref: '72.062', name: 'Earth', range: 'Game Color', hex: '#563d25' },
  { brand: 'Vallejo', ref: '72.063', name: 'Desert Yellow', range: 'Game Color', hex: '#7b5b2c' },
  { brand: 'Vallejo', ref: '72.066', name: 'Tan', range: 'Game Color', hex: '#7d4c3e' },
  { brand: 'Vallejo', ref: '72.067', name: 'Cayman Green', range: 'Game Color', hex: '#41391a' },
  { brand: 'Vallejo', ref: '72.071', name: 'Barbarian Skin', range: 'Game Color', hex: '#785a3f' },
  { brand: 'Vallejo', ref: '72.076', name: 'Alien Purple', range: 'Game Color', hex: '#53417c' },
  { brand: 'Vallejo', ref: '72.082', name: 'White', range: 'Game Color', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '72.083', name: 'Magenta', range: 'Game Color', hex: '#9b2242' },
  { brand: 'Vallejo', ref: '72.084', name: 'Dark Turquoise', range: 'Game Color', hex: '#043e3d' },
  { brand: 'Vallejo', ref: '72.085', name: 'Yellow', range: 'Game Color', hex: '#e99c12' },
  { brand: 'Vallejo', ref: '72.086', name: 'Red', range: 'Game Color', hex: '#a71521' },
  { brand: 'Vallejo', ref: '72.087', name: 'Violet', range: 'Game Color', hex: '#49315e' },
  { brand: 'Vallejo', ref: '72.088', name: 'Blue', range: 'Game Color', hex: '#153768' },
  { brand: 'Vallejo', ref: '72.089', name: 'Green', range: 'Game Color', hex: '#007033' },
  { brand: 'Vallejo', ref: '72.090', name: 'Black Green', range: 'Game Color', hex: '#253b2b' },
  { brand: 'Vallejo', ref: '72.091', name: 'Sepia', range: 'Game Color', hex: '#342613' },
  { brand: 'Vallejo', ref: '72.093', name: 'Skin', range: 'Game Color', hex: '#452118' },
  { brand: 'Vallejo', ref: '72.094', name: 'Black', range: 'Game Color', hex: '#000000' },
  { brand: 'Vallejo', ref: '72.095', name: 'Glacier Blue', range: 'Game Color', hex: '#b7d0ec' },
  { brand: 'Vallejo', ref: '72.096', name: 'Verdigris', range: 'Game Color', hex: '#86c7aa' },
  { brand: 'Vallejo', ref: '72.098', name: 'Elfi c Flesh', range: 'Game Color', hex: '#f1d5a3' },
  { brand: 'Vallejo', ref: '72.099', name: 'Skin Tone', range: 'Game Color', hex: '#e4ac84' },
  { brand: 'Vallejo', ref: '72.100', name: 'Rosy Flesh', range: 'Game Color', hex: '#e17262' },
  { brand: 'Vallejo', ref: '72.101', name: 'Off-White', range: 'Game Color', hex: '#ffefb8' },
  { brand: 'Vallejo', ref: '72.102', name: 'Steel Grey', range: 'Game Color', hex: '#4a5a62' },
  { brand: 'Vallejo', ref: '72.103', name: 'Fluorescent Yellow', range: 'Game Color', hex: '#faeb3d' },
  { brand: 'Vallejo', ref: '72.104', name: 'Fluorescent Green', range: 'Game Color', hex: '#5ab031' },
  { brand: 'Vallejo', ref: '72.106', name: 'Scarlet Blood', range: 'Game Color', hex: '#ac1f1d' },
  { brand: 'Vallejo', ref: '72.107', name: 'Athena Skin', range: 'Game Color', hex: '#b46354' },
  { brand: 'Vallejo', ref: '72.108', name: 'Succubus Skin', range: 'Game Color', hex: '#73423b' },
  { brand: 'Vallejo', ref: '72.109', name: 'Toxic Yellow', range: 'Game Color', hex: '#e2c33a' },
  { brand: 'Vallejo', ref: '72.110', name: 'Sunset Orange', range: 'Game Color', hex: '#f08331' },
  { brand: 'Vallejo', ref: '72.111', name: 'Nocturnal Red', range: 'Game Color', hex: '#551d22' },
  { brand: 'Vallejo', ref: '72.112', name: 'Evil Red', range: 'Game Color', hex: '#451f25' },
  { brand: 'Vallejo', ref: '72.113', name: 'Deep Magenta', range: 'Game Color', hex: '#4a1b2f' },
  { brand: 'Vallejo', ref: '72.114', name: 'Lustful Purple', range: 'Game Color', hex: '#7d6092' },
  { brand: 'Vallejo', ref: '72.115', name: 'Grunge Brown', range: 'Game Color', hex: '#69361c' },
  { brand: 'Vallejo', ref: '72.116', name: 'Midnight Purple', range: 'Game Color', hex: '#251531' },
  { brand: 'Vallejo', ref: '72.117', name: 'Elfi c Blue', range: 'Game Color', hex: '#3d5474' },
  { brand: 'Vallejo', ref: '72.118', name: 'Sunrise Blue', range: 'Game Color', hex: '#60b8e0' },
  { brand: 'Vallejo', ref: '72.119', name: 'Aquamarine', range: 'Game Color', hex: '#007c74' },
  { brand: 'Vallejo', ref: '72.120', name: 'Abyssal Turquoise', range: 'Game Color', hex: '#132332' },
  { brand: 'Vallejo', ref: '72.121', name: 'Ghost Green', range: 'Game Color', hex: '#5bb889' },
  { brand: 'Vallejo', ref: '72.122', name: 'Bile Green', range: 'Game Color', hex: '#d5d900' },
  { brand: 'Vallejo', ref: '72.123', name: 'Angel Green', range: 'Game Color', hex: '#233822' },
  { brand: 'Vallejo', ref: '72.124', name: 'Gorgon Brown', range: 'Game Color', hex: '#3e2317' },
  { brand: 'Vallejo', ref: '72.145', name: 'Dirty Grey', range: 'Game Color', hex: '#493d20' },
  { brand: 'Vallejo', ref: '72.148', name: 'Warm Grey', range: 'Game Color', hex: '#80655e' },
  { brand: 'Vallejo', ref: '72.155', name: 'Charcoal', range: 'Game Color', hex: '#18170f' },
  { brand: 'Vallejo', ref: '72.156', name: 'Fluorescent Orange', range: 'Game Color', hex: '#e63b11' },
  { brand: 'Vallejo', ref: '72.157', name: 'Fluorescent Red', range: 'Game Color', hex: '#e42e3e' },
  { brand: 'Vallejo', ref: '72.158', name: 'Fluorescent Magenta', range: 'Game Color', hex: '#e8348b' },
  { brand: 'Vallejo', ref: '72.159', name: 'Fluorescent Violet', range: 'Game Color', hex: '#6e257a' },
  { brand: 'Vallejo', ref: '72.160', name: 'Fluorescent Blue', range: 'Game Color', hex: '#007ab9' },
  { brand: 'Vallejo', ref: '72.161', name: 'Fluorescent Cold Green', range: 'Game Color', hex: '#00604d' },
  { brand: 'Vallejo', ref: '69.001', name: 'Pure White', range: 'Mecha Color', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '69.002', name: 'White Grey', range: 'Mecha Color', hex: '#bdbaa9' },
  { brand: 'Vallejo', ref: '69.003', name: 'Off-White', range: 'Mecha Color', hex: '#ebe3c9' },
  { brand: 'Vallejo', ref: '69.004', name: 'Yellow', range: 'Mecha Color', hex: '#e69800' },
  { brand: 'Vallejo', ref: '69.005', name: 'Light Flesh', range: 'Mecha Color', hex: '#fbc991' },
  { brand: 'Vallejo', ref: '69.006', name: 'Pink', range: 'Mecha Color', hex: '#d5745f' },
  { brand: 'Vallejo', ref: '69.007', name: 'Orange', range: 'Mecha Color', hex: '#e84b19' },
  { brand: 'Vallejo', ref: '69.008', name: 'Red', range: 'Mecha Color', hex: '#a8201b' },
  { brand: 'Vallejo', ref: '69.009', name: 'SZ Red', range: 'Mecha Color', hex: '#912322' },
  { brand: 'Vallejo', ref: '69.010', name: 'Magenta', range: 'Mecha Color', hex: '#8b2a5f' },
  { brand: 'Vallejo', ref: '69.011', name: 'Dark Red', range: 'Mecha Color', hex: '#601320' },
  { brand: 'Vallejo', ref: '69.012', name: 'Purple', range: 'Mecha Color', hex: '#8f6aa5' },
  { brand: 'Vallejo', ref: '69.013', name: 'Titan Blue', range: 'Mecha Color', hex: '#121e2d' },
  { brand: 'Vallejo', ref: '69.014', name: 'Grey Green', range: 'Mecha Color', hex: '#465759' },
  { brand: 'Vallejo', ref: '69.015', name: 'Blue Grey', range: 'Mecha Color', hex: '#46656f' },
  { brand: 'Vallejo', ref: '69.016', name: 'Light Blue', range: 'Mecha Color', hex: '#435f7a' },
  { brand: 'Vallejo', ref: '69.017', name: 'Sky Blue', range: 'Mecha Color', hex: '#08abce' },
  { brand: 'Vallejo', ref: '69.018', name: 'Deep Blue', range: 'Mecha Color', hex: '#005f92' },
  { brand: 'Vallejo', ref: '69.019', name: 'Blue', range: 'Mecha Color', hex: '#1c2347' },
  { brand: 'Vallejo', ref: '69.020', name: 'Electric Blue', range: 'Mecha Color', hex: '#1b245c' },
  { brand: 'Vallejo', ref: '69.021', name: 'Dark Blue', range: 'Mecha Color', hex: '#20313f' },
  { brand: 'Vallejo', ref: '69.022', name: 'Titan Dark Blue', range: 'Mecha Color', hex: '#121c1c' },
  { brand: 'Vallejo', ref: '69.023', name: 'Turquoise', range: 'Mecha Color', hex: '#00777b' },
  { brand: 'Vallejo', ref: '69.024', name: 'Stone Grey', range: 'Mecha Color', hex: '#768c89' },
  { brand: 'Vallejo', ref: '69.025', name: 'Light Green', range: 'Mecha Color', hex: '#b8b8a7' },
  { brand: 'Vallejo', ref: '69.026', name: 'Green', range: 'Mecha Color', hex: '#76826a' },
  { brand: 'Vallejo', ref: '69.027', name: 'Green Blue', range: 'Mecha Color', hex: '#618662' },
  { brand: 'Vallejo', ref: '69.028', name: 'Olive Green', range: 'Mecha Color', hex: '#50623c' },
  { brand: 'Vallejo', ref: '69.029', name: 'Deep Green', range: 'Mecha Color', hex: '#646d57' },
  { brand: 'Vallejo', ref: '69.030', name: 'Dark Green', range: 'Mecha Color', hex: '#353525' },
  { brand: 'Vallejo', ref: '69.031', name: 'Grey Sand', range: 'Mecha Color', hex: '#908472' },
  { brand: 'Vallejo', ref: '69.032', name: 'Yellow Ochre', range: 'Mecha Color', hex: '#ae7020' },
  { brand: 'Vallejo', ref: '69.033', name: 'Sand Yellow', range: 'Mecha Color', hex: '#f5bf57' },
  { brand: 'Vallejo', ref: '69.034', name: 'Brown', range: 'Mecha Color', hex: '#6a4b31' },
  { brand: 'Vallejo', ref: '69.035', name: 'Chipping Brown', range: 'Mecha Color', hex: '#2b1e17' },
  { brand: 'Vallejo', ref: '69.036', name: 'Light Grey', range: 'Mecha Color', hex: '#77817e' },
  { brand: 'Vallejo', ref: '69.037', name: 'Grey', range: 'Mecha Color', hex: '#5c6760' },
  { brand: 'Vallejo', ref: '69.038', name: 'Medium Grey', range: 'Mecha Color', hex: '#5a5b5b' },
  { brand: 'Vallejo', ref: '69.039', name: 'Grey Z', range: 'Mecha Color', hex: '#50524e' },
  { brand: 'Vallejo', ref: '69.040', name: 'Phantom Grey', range: 'Mecha Color', hex: '#222c2e' },
  { brand: 'Vallejo', ref: '69.041', name: 'Dark Grey Green', range: 'Mecha Color', hex: '#34312f' },
  { brand: 'Vallejo', ref: '69.042', name: 'Pure Black', range: 'Mecha Color', hex: '#000000' },
  { brand: 'Vallejo', ref: '69.054', name: 'Yellow Fluorescent', range: 'Mecha Color', hex: '#e0de12' },
  { brand: 'Vallejo', ref: '69.055', name: 'Orange Fluorescent', range: 'Mecha Color', hex: '#e84610' },
  { brand: 'Vallejo', ref: '69.056', name: 'Magenta Fluorescent', range: 'Mecha Color', hex: '#e40074' },
  { brand: 'Vallejo', ref: '69.057', name: 'Green Fluorescent', range: 'Mecha Color', hex: '#27a737' },
  { brand: 'Vallejo', ref: '69.505', name: 'Light Rust Wash', range: 'Mecha Color', hex: '#eb7717' },
  { brand: 'Vallejo', ref: '69.507', name: 'Dark Rust Wash', range: 'Mecha Color', hex: '#e1580a' },
  { brand: 'Vallejo', ref: '69.515', name: 'Light Grey Wash', range: 'Mecha Color', hex: '#c8c8c6' },
  { brand: 'Vallejo', ref: '69.518', name: 'Black Wash', range: 'Mecha Color', hex: '#000000' },
  { brand: 'Vallejo', ref: '69.521', name: 'Oiled Earth Wash', range: 'Mecha Color', hex: '#6d5b4f' },
  { brand: 'Vallejo', ref: '69.522', name: 'Desert Dust Wash', range: 'Mecha Color', hex: '#d8bd80' },
  { brand: 'Vallejo', ref: '69.813', name: 'Oil Stains (Gloss)', range: 'Mecha Color', hex: '#755419' },
  { brand: 'Vallejo', ref: '69.814', name: 'Fuel Stains (Gloss)', range: 'Mecha Color', hex: '#a06314' },
  { brand: 'Vallejo', ref: '69.817', name: 'Petrol Spills (Gloss)', range: 'Mecha Color', hex: '#1a1d1f' },
  { brand: 'Vallejo', ref: '69.818', name: 'Brown Eng. Soot (Matt)', range: 'Mecha Color', hex: '#60361d' },
  { brand: 'Vallejo', ref: '69.821', name: 'Rust Texture (Matt)', range: 'Mecha Color', hex: '#6a3329' },
  { brand: 'Vallejo', ref: '71.001', name: 'White', range: 'Model Air', hex: '#f9faf9' },
  { brand: 'Vallejo', ref: '71.002', name: 'Medium Yellow', range: 'Model Air', hex: '#f9b000' },
  { brand: 'Vallejo', ref: '71.003', name: 'Red RLM23', range: 'Model Air', hex: '#c82517' },
  { brand: 'Vallejo', ref: '71.004', name: 'Blue', range: 'Model Air', hex: '#354168' },
  { brand: 'Vallejo', ref: '71.005', name: 'Grey Blue', range: 'Model Air', hex: '#474b59' },
  { brand: 'Vallejo', ref: '71.006', name: 'Light Green Chrom.', range: 'Model Air', hex: '#606845' },
  { brand: 'Vallejo', ref: '71.007', name: 'Olive Green', range: 'Model Air', hex: '#373b3a' },
  { brand: 'Vallejo', ref: '71.008', name: 'Pale Blue', range: 'Model Air', hex: '#759499' },
  { brand: 'Vallejo', ref: '71.009', name: 'Eau de Nil “D.E.Green”', range: 'Model Air', hex: '#aab981' },
  { brand: 'Vallejo', ref: '71.010', name: 'Interior Green', range: 'Model Air', hex: '#675f41' },
  { brand: 'Vallejo', ref: '71.011', name: 'Dark Green RLM83', range: 'Model Air', hex: '#525047' },
  { brand: 'Vallejo', ref: '71.012', name: 'Dark Green', range: 'Model Air', hex: '#575643' },
  { brand: 'Vallejo', ref: '71.013', name: 'Yellow Olive', range: 'Model Air', hex: '#474844' },
  { brand: 'Vallejo', ref: '71.014', name: 'Gunship Green', range: 'Model Air', hex: '#4d5846' },
  { brand: 'Vallejo', ref: '71.015', name: 'Dark Green RLM71', range: 'Model Air', hex: '#514a30' },
  { brand: 'Vallejo', ref: '71.016', name: 'USAF Olive Drab', range: 'Model Air', hex: '#655d49' },
  { brand: 'Vallejo', ref: '71.017', name: 'Russian Green 4BO', range: 'Model Air', hex: '#575545' },
  { brand: 'Vallejo', ref: '71.018', name: 'Black Green', range: 'Model Air', hex: '#484f50' },
  { brand: 'Vallejo', ref: '71.019', name: 'Camouf. Dark Green', range: 'Model Air', hex: '#4f514b' },
  { brand: 'Vallejo', ref: '71.020', name: 'Green Brown', range: 'Model Air', hex: '#4e4d42' },
  { brand: 'Vallejo', ref: '71.021', name: 'Black Green RLM70', range: 'Model Air', hex: '#454b48' },
  { brand: 'Vallejo', ref: '71.022', name: 'Light Green RLM82', range: 'Model Air', hex: '#4d5240' },
  { brand: 'Vallejo', ref: '71.023', name: 'Hemp', range: 'Model Air', hex: '#857a5d' },
  { brand: 'Vallejo', ref: '71.024', name: 'Khaki Brown', range: 'Model Air', hex: '#92795c' },
  { brand: 'Vallejo', ref: '71.025', name: 'Dark Yellow', range: 'Model Air', hex: '#967a49' },
  { brand: 'Vallejo', ref: '71.026', name: 'USA Flat Brown', range: 'Model Air', hex: '#896847' },
  { brand: 'Vallejo', ref: '71.027', name: 'Light Brown', range: 'Model Air', hex: '#b19268' },
  { brand: 'Vallejo', ref: '71.028', name: 'Sand Yellow', range: 'Model Air', hex: '#a38d72' },
  { brand: 'Vallejo', ref: '71.029', name: 'Dark Earth', range: 'Model Air', hex: '#625644' },
  { brand: 'Vallejo', ref: '71.030', name: 'Brown Green', range: 'Model Air', hex: '#917049' },
  { brand: 'Vallejo', ref: '71.031', name: 'Middle Stone', range: 'Model Air', hex: '#997e50' },
  { brand: 'Vallejo', ref: '71.032', name: 'Golden Brown', range: 'Model Air', hex: '#876441' },
  { brand: 'Vallejo', ref: '71.033', name: 'Yellow Ochre', range: 'Model Air', hex: '#d9922e' },
  { brand: 'Vallejo', ref: '71.034', name: 'Sand Brown', range: 'Model Air', hex: '#976b54' },
  { brand: 'Vallejo', ref: '71.035', name: 'Camouf. Pale Brown', range: 'Model Air', hex: '#705947' },
  { brand: 'Vallejo', ref: '71.036', name: 'Mahogany', range: 'Model Air', hex: '#4d3d36' },
  { brand: 'Vallejo', ref: '71.037', name: 'Mud Brown', range: 'Model Air', hex: '#8e664c' },
  { brand: 'Vallejo', ref: '71.038', name: 'Cam. Medium Brown', range: 'Model Air', hex: '#625142' },
  { brand: 'Vallejo', ref: '71.039', name: 'Hull Red', range: 'Model Air', hex: '#483732' },
  { brand: 'Vallejo', ref: '71.040', name: 'Burnt Umber', range: 'Model Air', hex: '#40332c' },
  { brand: 'Vallejo', ref: '71.041', name: 'Armour Brown', range: 'Model Air', hex: '#453b38' },
  { brand: 'Vallejo', ref: '71.042', name: 'Dark Brown RLM61', range: 'Model Air', hex: '#4a3f3a' },
  { brand: 'Vallejo', ref: '71.043', name: 'US Olive Drab', range: 'Model Air', hex: '#5c5347' },
  { brand: 'Vallejo', ref: '71.044', name: 'Grey RLM02', range: 'Model Air', hex: '#767463' },
  { brand: 'Vallejo', ref: '71.045', name: 'Cement Grey', range: 'Model Air', hex: '#909482' },
  { brand: 'Vallejo', ref: '71.046', name: 'Pale Blue Grey', range: 'Model Air', hex: '#969ca0' },
  { brand: 'Vallejo', ref: '71.047', name: 'Grey', range: 'Model Air', hex: '#575b62' },
  { brand: 'Vallejo', ref: '71.048', name: 'Engine Gray', range: 'Model Air', hex: '#535b67' },
  { brand: 'Vallejo', ref: '71.049', name: 'Sea Grey', range: 'Model Air', hex: '#666971' },
  { brand: 'Vallejo', ref: '71.050', name: 'Light Gray', range: 'Model Air', hex: '#8e9397' },
  { brand: 'Vallejo', ref: '71.051', name: 'Neutral Gray', range: 'Model Air', hex: '#72787d' },
  { brand: 'Vallejo', ref: '71.052', name: 'Anthracite Grey', range: 'Model Air', hex: '#505255' },
  { brand: 'Vallejo', ref: '71.053', name: 'Dark Sea Gray', range: 'Model Air', hex: '#51565b' },
  { brand: 'Vallejo', ref: '71.054', name: 'Dark Grey Blue', range: 'Model Air', hex: '#4b4e55' },
  { brand: 'Vallejo', ref: '71.055', name: 'Black Grey RLM66', range: 'Model Air', hex: '#515557' },
  { brand: 'Vallejo', ref: '71.056', name: 'Panzer Dark Grey', range: 'Model Air', hex: '#474749' },
  { brand: 'Vallejo', ref: '71.057', name: 'Black', range: 'Model Air', hex: '#323132' },
  { brand: 'Vallejo', ref: '71.074', name: 'Beige', range: 'Model Air', hex: '#e6c580' },
  { brand: 'Vallejo', ref: '71.075', name: 'Ivory', range: 'Model Air', hex: '#c1ae89' },
  { brand: 'Vallejo', ref: '71.076', name: 'Skin Tone', range: 'Model Air', hex: '#f9c391' },
  { brand: 'Vallejo', ref: '71.077', name: 'Wood', range: 'Model Air', hex: '#a9743b' },
  { brand: 'Vallejo', ref: '71.078', name: 'Yellow RLM04', range: 'Model Air', hex: '#e89f22' },
  { brand: 'Vallejo', ref: '71.079', name: 'Tan Earth', range: 'Model Air', hex: '#a8816c' },
  { brand: 'Vallejo', ref: '71.080', name: 'Rust', range: 'Model Air', hex: '#765750' },
  { brand: 'Vallejo', ref: '71.081', name: 'Ochre', range: 'Model Air', hex: '#7a6a3c' },
  { brand: 'Vallejo', ref: '71.082', name: 'Fluorescent Red', range: 'Model Air', hex: '#ec604d' },
  { brand: 'Vallejo', ref: '71.083', name: 'Orange', range: 'Model Air', hex: '#e4481f' },
  { brand: 'Vallejo', ref: '71.084', name: 'Fire Red', range: 'Model Air', hex: '#873e31' },
  { brand: 'Vallejo', ref: '71.085', name: 'Ferrari Red', range: 'Model Air', hex: '#af362b' },
  { brand: 'Vallejo', ref: '71.086', name: 'Light Red', range: 'Model Air', hex: '#e1431e' },
  { brand: 'Vallejo', ref: '71.087', name: 'Steel Blue', range: 'Model Air', hex: '#1c3f55' },
  { brand: 'Vallejo', ref: '71.088', name: 'French Blue', range: 'Model Air', hex: '#2a4570' },
  { brand: 'Vallejo', ref: '71.089', name: 'Light Sea Blue', range: 'Model Air', hex: '#00a4d8' },
  { brand: 'Vallejo', ref: '71.090', name: 'Deep Sky', range: 'Model Air', hex: '#273956' },
  { brand: 'Vallejo', ref: '71.091', name: 'Signal Blue', range: 'Model Air', hex: '#2a3340' },
  { brand: 'Vallejo', ref: '71.092', name: 'Medium Olive', range: 'Model Air', hex: '#535545' },
  { brand: 'Vallejo', ref: '71.093', name: 'NATO Green', range: 'Model Air', hex: '#555b50' },
  { brand: 'Vallejo', ref: '71.094', name: 'Green Zinc Chromate', range: 'Model Air', hex: '#58613c' },
  { brand: 'Vallejo', ref: '71.095', name: 'Pale Green', range: 'Model Air', hex: '#728354' },
  { brand: 'Vallejo', ref: '71.096', name: 'Olive Grey', range: 'Model Air', hex: '#616758' },
  { brand: 'Vallejo', ref: '71.097', name: 'Medium Gunship Gray', range: 'Model Air', hex: '#5c6067' },
  { brand: 'Vallejo', ref: '71.101', name: 'Light Blue RLM78', range: 'Model Air', hex: '#819596' },
  { brand: 'Vallejo', ref: '71.102', name: 'Red', range: 'Model Air', hex: '#b32c32' },
  { brand: 'Vallejo', ref: '71.103', name: 'Grey Blue RLM84', range: 'Model Air', hex: '#a1a49a' },
  { brand: 'Vallejo', ref: '71.104', name: 'Green RLM62', range: 'Model Air', hex: '#5d5f46' },
  { brand: 'Vallejo', ref: '71.105', name: 'Brown RLM26', range: 'Model Air', hex: '#874237' },
  { brand: 'Vallejo', ref: '71.106', name: 'Ivory RLM05', range: 'Model Air', hex: '#c6b36b' },
  { brand: 'Vallejo', ref: '71.107', name: 'US Interior Yellow', range: 'Model Air', hex: '#cca553' },
  { brand: 'Vallejo', ref: '71.108', name: 'UK Azure Blue', range: 'Model Air', hex: '#718caf' },
  { brand: 'Vallejo', ref: '71.109', name: 'Faded P.R.U. Blue', range: 'Model Air', hex: '#546e77' },
  { brand: 'Vallejo', ref: '71.110', name: 'Dark Gray', range: 'Model Air', hex: '#565a5d' },
  { brand: 'Vallejo', ref: '71.111', name: 'USAF Light Blue', range: 'Model Air', hex: '#556978' },
  { brand: 'Vallejo', ref: '71.112', name: 'Sand', range: 'Model Air', hex: '#9f867c' },
  { brand: 'Vallejo', ref: '71.113', name: 'IDF Blue', range: 'Model Air', hex: '#537588' },
  { brand: 'Vallejo', ref: '71.114', name: 'Medium Gray', range: 'Model Air', hex: '#6b7f83' },
  { brand: 'Vallejo', ref: '71.115', name: 'Blue Grey', range: 'Model Air', hex: '#484c53' },
  { brand: 'Vallejo', ref: '71.116', name: 'Camouf. Grey Green', range: 'Model Air', hex: '#7d6b4f' },
  { brand: 'Vallejo', ref: '71.117', name: 'Camouflage Brown', range: 'Model Air', hex: '#b0906f' },
  { brand: 'Vallejo', ref: '71.118', name: 'Camouflage Grey', range: 'Model Air', hex: '#88765a' },
  { brand: 'Vallejo', ref: '71.119', name: 'White Grey', range: 'Model Air', hex: '#d9d7cc' },
  { brand: 'Vallejo', ref: '71.120', name: 'Dark Ghost Gray', range: 'Model Air', hex: '#8c979f' },
  { brand: 'Vallejo', ref: '71.121', name: 'Light Gull Gray', range: 'Model Air', hex: '#a9aba5' },
  { brand: 'Vallejo', ref: '71.122', name: 'US Desert Armour 686', range: 'Model Air', hex: '#ae9a81' },
  { brand: 'Vallejo', ref: '71.123', name: 'Dark Grey RLM42', range: 'Model Air', hex: '#555557' },
  { brand: 'Vallejo', ref: '71.124', name: 'USAF Green', range: 'Model Air', hex: '#505c5c' },
  { brand: 'Vallejo', ref: '71.125', name: 'USAF Brown', range: 'Model Air', hex: '#8c7260' },
  { brand: 'Vallejo', ref: '71.126', name: 'IDF/IAF Green', range: 'Model Air', hex: '#788870' },
  { brand: 'Vallejo', ref: '71.128', name: 'Gray Violet', range: 'Model Air', hex: '#686561' },
  { brand: 'Vallejo', ref: '71.129', name: 'Light Rust', range: 'Model Air', hex: '#916045' },
  { brand: 'Vallejo', ref: '71.130', name: 'Orange Rust', range: 'Model Air', hex: '#c76632' },
  { brand: 'Vallejo', ref: '71.131', name: 'Concrete', range: 'Model Air', hex: '#797064' },
  { brand: 'Vallejo', ref: '71.132', name: 'Aged White', range: 'Model Air', hex: '#e4d3b2' },
  { brand: 'Vallejo', ref: '71.133', name: 'Dirt', range: 'Model Air', hex: '#7b6342' },
  { brand: 'Vallejo', ref: '71.134', name: 'IJA Midouri Green', range: 'Model Air', hex: '#424c3e' },
  { brand: 'Vallejo', ref: '71.135', name: 'IJA Chrome Yellow', range: 'Model Air', hex: '#f4a700' },
  { brand: 'Vallejo', ref: '71.136', name: 'IJA Earth Brown', range: 'Model Air', hex: '#7b654f' },
  { brand: 'Vallejo', ref: '71.137', name: 'US Light Green', range: 'Model Air', hex: '#696643' },
  { brand: 'Vallejo', ref: '71.138', name: 'US Sand', range: 'Model Air', hex: '#96866a' },
  { brand: 'Vallejo', ref: '71.139', name: 'US Field Drab', range: 'Model Air', hex: '#6d5c44' },
  { brand: 'Vallejo', ref: '71.140', name: 'US Desert Sand', range: 'Model Air', hex: '#a98e7c' },
  { brand: 'Vallejo', ref: '71.141', name: 'IDF Sand Grey 73', range: 'Model Air', hex: '#ab9f87' },
  { brand: 'Vallejo', ref: '71.142', name: 'IDF Sinai Grey 82', range: 'Model Air', hex: '#7b7467' },
  { brand: 'Vallejo', ref: '71.143', name: 'UK Light Stone', range: 'Model Air', hex: '#b39b6a' },
  { brand: 'Vallejo', ref: '71.244', name: 'Sand Beige', range: 'Model Air', hex: '#b79f7e' },
  { brand: 'Vallejo', ref: '71.245', name: 'Loam Beige', range: 'Model Air', hex: '#988865' },
  { brand: 'Vallejo', ref: '71.246', name: 'Yellow Brown', range: 'Model Air', hex: '#98866a' },
  { brand: 'Vallejo', ref: '71.247', name: 'Light Olive', range: 'Model Air', hex: '#69624a' },
  { brand: 'Vallejo', ref: '71.248', name: 'Brown Grey', range: 'Model Air', hex: '#676259' },
  { brand: 'Vallejo', ref: '71.249', name: 'NATO Brown', range: 'Model Air', hex: '#5f4f47' },
  { brand: 'Vallejo', ref: '71.250', name: 'Bronze Green', range: 'Model Air', hex: '#57584c' },
  { brand: 'Vallejo', ref: '71.251', name: 'NATO Black', range: 'Model Air', hex: '#333233' },
  { brand: 'Vallejo', ref: '71.255', name: 'Light Blue RLM65', range: 'Model Air', hex: '#8a9f9b' },
  { brand: 'Vallejo', ref: '71.256', name: 'Green RLM73', range: 'Model Air', hex: '#474e48' },
  { brand: 'Vallejo', ref: '71.257', name: 'Light Blue RLM76', range: 'Model Air', hex: '#98aaa7' },
  { brand: 'Vallejo', ref: '71.258', name: 'Grey Green RLM74', range: 'Model Air', hex: '#545651' },
  { brand: 'Vallejo', ref: '71.259', name: 'Grey Violet RLM75', range: 'Model Air', hex: '#646567' },
  { brand: 'Vallejo', ref: '71.260', name: 'Light Grey RLM63', range: 'Model Air', hex: '#6d7064' },
  { brand: 'Vallejo', ref: '71.262', name: 'Airbrush', range: 'Model Air', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '71.263', name: 'Green RLM72', range: 'Model Air', hex: '#474741' },
  { brand: 'Vallejo', ref: '71.264', name: 'Brown Violet RLM81', range: 'Model Air', hex: '#675d4d' },
  { brand: 'Vallejo', ref: '71.265', name: 'Olive Green RLM80', range: 'Model Air', hex: '#4b5041' },
  { brand: 'Vallejo', ref: '71.266', name: 'Dark Blue RLM24', range: 'Model Air', hex: '#374962' },
  { brand: 'Vallejo', ref: '71.267', name: 'Light Green RLM25', range: 'Model Air', hex: '#4a796d' },
  { brand: 'Vallejo', ref: '71.268', name: 'German Grey', range: 'Model Air', hex: '#494b44' },
  { brand: 'Vallejo', ref: '71.269', name: 'Red', range: 'Model Air', hex: '#9f3d34' },
  { brand: 'Vallejo', ref: '71.270', name: 'Off-White', range: 'Model Air', hex: '#e6d9be' },
  { brand: 'Vallejo', ref: '71.271', name: 'German Red Brown', range: 'Model Air', hex: '#684339' },
  { brand: 'Vallejo', ref: '71.272', name: 'German Yellow Brown', range: 'Model Air', hex: '#856f4c' },
  { brand: 'Vallejo', ref: '71.273', name: 'Ocean Gray', range: 'Model Air', hex: '#6d7682' },
  { brand: 'Vallejo', ref: '71.274', name: 'Aggressor Gray', range: 'Model Air', hex: '#7c7d82' },
  { brand: 'Vallejo', ref: '71.275', name: 'USAF Medium Gray', range: 'Model Air', hex: '#83848b' },
  { brand: 'Vallejo', ref: '71.276', name: 'USAF Light Gray', range: 'Model Air', hex: '#c2c5c0' },
  { brand: 'Vallejo', ref: '71.277', name: 'Dark Gull Gray', range: 'Model Air', hex: '#828383' },
  { brand: 'Vallejo', ref: '71.278', name: 'Sand Yellow RLM79', range: 'Model Air', hex: '#967651' },
  { brand: 'Vallejo', ref: '71.279', name: 'Insignia White', range: 'Model Air', hex: '#e2e3d5' },
  { brand: 'Vallejo', ref: '71.280', name: 'Camouflage Gray', range: 'Model Air', hex: '#6c6d6b' },
  { brand: 'Vallejo', ref: '71.281', name: '3B Russian Green', range: 'Model Air', hex: '#484845' },
  { brand: 'Vallejo', ref: '71.282', name: '6K Russian Brown', range: 'Model Air', hex: '#4d4541' },
  { brand: 'Vallejo', ref: '71.283', name: '7K Russian Tan', range: 'Model Air', hex: '#7c725c' },
  { brand: 'Vallejo', ref: '71.284', name: 'UK Light Mud', range: 'Model Air', hex: '#857f70' },
  { brand: 'Vallejo', ref: '71.285', name: 'IJA Dark Green', range: 'Model Air', hex: '#575545' },
  { brand: 'Vallejo', ref: '71.286', name: 'IJA Olive Green', range: 'Model Air', hex: '#514a30' },
  { brand: 'Vallejo', ref: '71.287', name: 'IJA Khaki Brown', range: 'Model Air', hex: '#6d5c44' },
  { brand: 'Vallejo', ref: '71.288', name: 'UK BSC 64 Portl. Stone', range: 'Model Air', hex: '#ccbd94' },
  { brand: 'Vallejo', ref: '71.289', name: 'US Dark Green', range: 'Model Air', hex: '#595a48' },
  { brand: 'Vallejo', ref: '71.290', name: 'US Earth Brown', range: 'Model Air', hex: '#60544a' },
  { brand: 'Vallejo', ref: '71.291', name: 'US Earth Yellow', range: 'Model Air', hex: '#b98e5f' },
  { brand: 'Vallejo', ref: '71.292', name: 'US Loam', range: 'Model Air', hex: '#53554c' },
  { brand: 'Vallejo', ref: '71.293', name: 'US Earth Red', range: 'Model Air', hex: '#7d6150' },
  { brand: 'Vallejo', ref: '71.294', name: 'US Forest Green', range: 'Model Air', hex: '#555548' },
  { brand: 'Vallejo', ref: '71.295', name: 'USN Sea Blue', range: 'Model Air', hex: '#44474d' },
  { brand: 'Vallejo', ref: '71.296', name: 'USAAF Light Gray', range: 'Model Air', hex: '#bdbbad' },
  { brand: 'Vallejo', ref: '71.297', name: 'JGSD Brown 3606', range: 'Model Air', hex: '#6b6158' },
  { brand: 'Vallejo', ref: '71.298', name: 'M495 Light Gray', range: 'Model Air', hex: '#9d9988' },
  { brand: 'Vallejo', ref: '71.299', name: 'Intermediate Blue', range: 'Model Air', hex: '#5d6a76' },
  { brand: 'Vallejo', ref: '71.300', name: 'Glossy Sea Blue', range: 'Model Air', hex: '#272d35' },
  { brand: 'Vallejo', ref: '71.301', name: 'AMT-4 Cam. Green', range: 'Model Air', hex: '#675f41' },
  { brand: 'Vallejo', ref: '71.302', name: 'Sky Type S', range: 'Model Air', hex: '#a2a48f' },
  { brand: 'Vallejo', ref: '71.303', name: 'A-24M Cam. Green', range: 'Model Air', hex: '#595a48' },
  { brand: 'Vallejo', ref: '71.304', name: 'AMT-11 Blue Grey', range: 'Model Air', hex: '#5c6067' },
  { brand: 'Vallejo', ref: '71.305', name: 'Interior Grey Green', range: 'Model Air', hex: '#96a28e' },
  { brand: 'Vallejo', ref: '71.306', name: 'Sky Blue', range: 'Model Air', hex: '#cbd9db' },
  { brand: 'Vallejo', ref: '71.307', name: 'BS Medium Sea Grey', range: 'Model Air', hex: '#838b8c' },
  { brand: 'Vallejo', ref: '71.308', name: 'AMT-12 Dark Grey', range: 'Model Air', hex: '#474950' },
  { brand: 'Vallejo', ref: '71.309', name: 'Dark Slate Grey', range: 'Model Air', hex: '#575643' },
  { brand: 'Vallejo', ref: '71.310', name: 'IJN Deep Dark Green', range: 'Model Air', hex: '#384f4e' },
  { brand: 'Vallejo', ref: '71.311', name: 'IJN Ash Grey', range: 'Model Air', hex: '#8a826e' },
  { brand: 'Vallejo', ref: '71.312', name: 'IJN Medium Grey', range: 'Model Air', hex: '#9c998d' },
  { brand: 'Vallejo', ref: '71.313', name: 'Dark Mediterr. Blue', range: 'Model Air', hex: '#29384f' },
  { brand: 'Vallejo', ref: '71.314', name: 'Seaplane Gray', range: 'Model Air', hex: '#585857' },
  { brand: 'Vallejo', ref: '71.315', name: 'Tire Black', range: 'Model Air', hex: '#464845' },
  { brand: 'Vallejo', ref: '71.316', name: 'N. 41 Dark Olive Drab', range: 'Model Air', hex: '#514a30' },
  { brand: 'Vallejo', ref: '71.317', name: 'AII SV. Gol Light Blue', range: 'Model Air', hex: '#7ac6da' },
  { brand: 'Vallejo', ref: '71.318', name: 'AMT-7 Greyish Blue', range: 'Model Air', hex: '#628b9c' },
  { brand: 'Vallejo', ref: '71.319', name: 'A-28M Greyish Blue', range: 'Model Air', hex: '#70a098' },
  { brand: 'Vallejo', ref: '71.320', name: 'AMT-1 Light Grey. Brown', range: 'Model Air', hex: '#958b7e' },
  { brand: 'Vallejo', ref: '71.321', name: 'IJA Light Grey Green', range: 'Model Air', hex: '#a5ab96' },
  { brand: 'Vallejo', ref: '71.322', name: 'IJN Black Green', range: 'Model Air', hex: '#424c3e' },
  { brand: 'Vallejo', ref: '71.323', name: 'BS Dark Earth', range: 'Model Air', hex: '#705d43' },
  { brand: 'Vallejo', ref: '71.324', name: 'BS Dark Green', range: 'Model Air', hex: '#484735' },
  { brand: 'Vallejo', ref: '71.325', name: 'IJN Dark Black Green', range: 'Model Air', hex: '#474844' },
  { brand: 'Vallejo', ref: '71.326', name: 'IJA Grey Green', range: 'Model Air', hex: '#bcb49c' },
  { brand: 'Vallejo', ref: '71.327', name: 'IAF Sand', range: 'Model Air', hex: '#bcad97' },
  { brand: 'Vallejo', ref: '71.328', name: 'Light Blue', range: 'Model Air', hex: '#c4cbbe' },
  { brand: 'Vallejo', ref: '71.329', name: 'Green', range: 'Model Air', hex: '#656c62' },
  { brand: 'Vallejo', ref: '71.330', name: 'Khaki Green N. 3', range: 'Model Air', hex: '#594e43' },
  { brand: 'Vallejo', ref: '71.331', name: 'Cockpit Emer. G.“Faded”', range: 'Model Air', hex: '#449886' },
  { brand: 'Vallejo', ref: '71.332', name: 'Underside Blue “Faded”', range: 'Model Air', hex: '#89b0c5' },
  { brand: 'Vallejo', ref: '71.333', name: 'Russian AF Blue', range: 'Model Air', hex: '#008fb9' },
  { brand: 'Vallejo', ref: '71.334', name: 'Flanker Light Blue', range: 'Model Air', hex: '#b1c9c3' },
  { brand: 'Vallejo', ref: '71.335', name: 'Flanker Light Gray', range: 'Model Air', hex: '#9ba6a1' },
  { brand: 'Vallejo', ref: '71.336', name: 'A-14 Steel Grey', range: 'Model Air', hex: '#69706f' },
  { brand: 'Vallejo', ref: '71.337', name: 'Flanker Blue', range: 'Model Air', hex: '#90aeb8' },
  { brand: 'Vallejo', ref: '71.338', name: 'Russian AF Grey Blue', range: 'Model Air', hex: '#a0acaa' },
  { brand: 'Vallejo', ref: '71.339', name: 'Russian AF Grey N.3', range: 'Model Air', hex: '#888e8d' },
  { brand: 'Vallejo', ref: '71.340', name: 'Grey Green', range: 'Model Air', hex: '#797e78' },
  { brand: 'Vallejo', ref: '71.341', name: 'Green Grey', range: 'Model Air', hex: '#5b6558' },
  { brand: 'Vallejo', ref: '71.342', name: 'Russian AF Light Blue', range: 'Model Air', hex: '#a9c9c4' },
  { brand: 'Vallejo', ref: '71.343', name: 'Russian AF Grey N.7', range: 'Model Air', hex: '#6f98af' },
  { brand: 'Vallejo', ref: '71.344', name: 'R. AF Grey Protec. Coat', range: 'Model Air', hex: '#b4ced5' },
  { brand: 'Vallejo', ref: '71.345', name: 'Russian AF Grey N.8', range: 'Model Air', hex: '#a0b4c2' },
  { brand: 'Vallejo', ref: '71.346', name: 'Russian AF Grey N.4', range: 'Model Air', hex: '#aca894' },
  { brand: 'Vallejo', ref: '71.347', name: 'Russian AF Dark Green', range: 'Model Air', hex: '#4e4939' },
  { brand: 'Vallejo', ref: '71.348', name: 'USAF Tan', range: 'Model Air', hex: '#c1976b' },
  { brand: 'Vallejo', ref: '70.400', name: 'Plastic Putty', range: 'Model Color', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '70.523', name: 'Liquid Mask', range: 'Model Color', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '70.540', name: 'Matt Base', range: 'Model Color', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '70.600', name: 'White', range: 'Model Color', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '70.602', name: 'Black', range: 'Model Color', hex: '#000000' },
  { brand: 'Vallejo', ref: '70.625', name: 'Ultramarine Blue', range: 'Model Color', hex: '#373a67' },
  { brand: 'Vallejo', ref: '70.629', name: 'Sun Yellow', range: 'Model Color', hex: '#f6a300' },
  { brand: 'Vallejo', ref: '70.630', name: 'Steel Grey', range: 'Model Color', hex: '#7a93a2' },
  { brand: 'Vallejo', ref: '70.631', name: 'Chainmail Silver', range: 'Model Color', hex: '#969ca2' },
  { brand: 'Vallejo', ref: '70.632', name: 'Bloody Red', range: 'Model Color', hex: '#d41d1b' },
  { brand: 'Vallejo', ref: '70.640', name: 'White', range: 'Model Color', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '70.641', name: 'Grey', range: 'Model Color', hex: '#c1c2c2' },
  { brand: 'Vallejo', ref: '70.642', name: 'Black', range: 'Model Color', hex: '#020203' },
  { brand: 'Vallejo', ref: '70.643', name: 'Ivory', range: 'Model Color', hex: '#f0ebcb' },
  { brand: 'Vallejo', ref: '70.644', name: 'Sand', range: 'Model Color', hex: '#c0a478' },
  { brand: 'Vallejo', ref: '70.740', name: 'Cam. Middle Brown', range: 'Model Color', hex: '#513e21' },
  { brand: 'Vallejo', ref: '70.741', name: 'Cam. Black Green', range: 'Model Color', hex: '#313028' },
  { brand: 'Vallejo', ref: '70.745', name: 'Dark Rose', range: 'Model Color', hex: '#805251' },
  { brand: 'Vallejo', ref: '70.746', name: 'Chestnut Brown', range: 'Model Color', hex: '#613f39' },
  { brand: 'Vallejo', ref: '70.747', name: 'Faded Red', range: 'Model Color', hex: '#ba584f' },
  { brand: 'Vallejo', ref: '70.748', name: 'Light Pink', range: 'Model Color', hex: '#e18da3' },
  { brand: 'Vallejo', ref: '70.749', name: 'Dark Purple', range: 'Model Color', hex: '#452734' },
  { brand: 'Vallejo', ref: '70.750', name: 'Light Violet', range: 'Model Color', hex: '#a893bb' },
  { brand: 'Vallejo', ref: '70.751', name: 'Black Violet', range: 'Model Color', hex: '#392a31' },
  { brand: 'Vallejo', ref: '70.752', name: 'Infantry Blue', range: 'Model Color', hex: '#25202c' },
  { brand: 'Vallejo', ref: '70.753', name: 'Light Blue Green', range: 'Model Color', hex: '#0097a5' },
  { brand: 'Vallejo', ref: '70.754', name: 'Continental Blue', range: 'Model Color', hex: '#25242b' },
  { brand: 'Vallejo', ref: '70.755', name: 'Light Emerald', range: 'Model Color', hex: '#007c73' },
  { brand: 'Vallejo', ref: '70.756', name: 'Splinter Green', range: 'Model Color', hex: '#446441' },
  { brand: 'Vallejo', ref: '70.757', name: 'Pacifi c Green', range: 'Model Color', hex: '#587064' },
  { brand: 'Vallejo', ref: '70.758', name: 'Bright Green', range: 'Model Color', hex: '#6f8349' },
  { brand: 'Vallejo', ref: '70.759', name: 'German Tank Crew', range: 'Model Color', hex: '#534b3e' },
  { brand: 'Vallejo', ref: '70.760', name: 'Light Mud', range: 'Model Color', hex: '#7a765a' },
  { brand: 'Vallejo', ref: '70.761', name: 'Old Wood', range: 'Model Color', hex: '#816d53' },
  { brand: 'Vallejo', ref: '70.762', name: 'Grey Brown', range: 'Model Color', hex: '#5c4922' },
  { brand: 'Vallejo', ref: '70.763', name: 'Canvas', range: 'Model Color', hex: '#4b3e1f' },
  { brand: 'Vallejo', ref: '70.764', name: 'Military Yellow', range: 'Model Color', hex: '#937726' },
  { brand: 'Vallejo', ref: '70.765', name: 'Desert Tan', range: 'Model Color', hex: '#b5a286' },
  { brand: 'Vallejo', ref: '70.766', name: 'Cream White', range: 'Model Color', hex: '#e1d2c3' },
  { brand: 'Vallejo', ref: '70.767', name: 'Desert Brown', range: 'Model Color', hex: '#ac8455' },
  { brand: 'Vallejo', ref: '70.768', name: 'BC Dark Brown', range: 'Model Color', hex: '#76573d' },
  { brand: 'Vallejo', ref: '70.769', name: 'Mustard Brown', range: 'Model Color', hex: '#9e7249' },
  { brand: 'Vallejo', ref: '70.770', name: 'New Wood', range: 'Model Color', hex: '#89613b' },
  { brand: 'Vallejo', ref: '70.771', name: 'Dark Rust', range: 'Model Color', hex: '#3c2525' },
  { brand: 'Vallejo', ref: '70.772', name: 'Medium Grey Blue', range: 'Model Color', hex: '#769c94' },
  { brand: 'Vallejo', ref: '70.773', name: 'Violet Grey', range: 'Model Color', hex: '#5a5a58' },
  { brand: 'Vallejo', ref: '70.774', name: 'Lavender Grey', range: 'Model Color', hex: '#7f6f6e' },
  { brand: 'Vallejo', ref: '70.802', name: 'Sunset Red', range: 'Model Color', hex: '#be2b4a' },
  { brand: 'Vallejo', ref: '70.803', name: 'Brown Rose', range: 'Model Color', hex: '#9c6660' },
  { brand: 'Vallejo', ref: '70.804', name: 'Beige Red', range: 'Model Color', hex: '#b16e4a' },
  { brand: 'Vallejo', ref: '70.805', name: 'German Orange', range: 'Model Color', hex: '#bc6255' },
  { brand: 'Vallejo', ref: '70.806', name: 'German Yellow', range: 'Model Color', hex: '#cdb65e' },
  { brand: 'Vallejo', ref: '70.807', name: 'Oxford Blue', range: 'Model Color', hex: '#3e3954' },
  { brand: 'Vallejo', ref: '70.808', name: 'Blue Green', range: 'Model Color', hex: '#007987' },
  { brand: 'Vallejo', ref: '70.809', name: 'Royal Blue', range: 'Model Color', hex: '#1a437e' },
  { brand: 'Vallejo', ref: '70.810', name: 'Royal Purple', range: 'Model Color', hex: '#4b2740' },
  { brand: 'Vallejo', ref: '70.811', name: 'Blue Violet', range: 'Model Color', hex: '#5e3876' },
  { brand: 'Vallejo', ref: '70.812', name: 'Violet Red', range: 'Model Color', hex: '#63353e' },
  { brand: 'Vallejo', ref: '70.814', name: 'Burnt Red', range: 'Model Color', hex: '#753c3a' },
  { brand: 'Vallejo', ref: '70.815', name: 'Basic Skin Tone', range: 'Model Color', hex: '#e9ac8d' },
  { brand: 'Vallejo', ref: '70.816', name: 'Luftwaffe Uniform', range: 'Model Color', hex: '#45414c' },
  { brand: 'Vallejo', ref: '70.817', name: 'Scarlet', range: 'Model Color', hex: '#c13d2e' },
  { brand: 'Vallejo', ref: '70.818', name: 'Red Leather', range: 'Model Color', hex: '#955439' },
  { brand: 'Vallejo', ref: '70.819', name: 'Iraqi Sand', range: 'Model Color', hex: '#b5925e' },
  { brand: 'Vallejo', ref: '70.820', name: 'Off-White', range: 'Model Color', hex: '#f4ede7' },
  { brand: 'Vallejo', ref: '70.821', name: 'Germ. Beige WWII', range: 'Model Color', hex: '#786a51' },
  { brand: 'Vallejo', ref: '70.822', name: 'Cam. Black Brown', range: 'Model Color', hex: '#413435' },
  { brand: 'Vallejo', ref: '70.823', name: 'Luftwaffe Green', range: 'Model Color', hex: '#373f25' },
  { brand: 'Vallejo', ref: '70.824', name: 'Orange Ochre', range: 'Model Color', hex: '#ab8136' },
  { brand: 'Vallejo', ref: '70.825', name: 'Pale Brown', range: 'Model Color', hex: '#9f8374' },
  { brand: 'Vallejo', ref: '70.826', name: 'Medium Brown', range: 'Model Color', hex: '#5b473b' },
  { brand: 'Vallejo', ref: '70.827', name: 'Lime Green', range: 'Model Color', hex: '#7d9334' },
  { brand: 'Vallejo', ref: '70.828', name: 'Mahogany Ink', range: 'Model Color', hex: '#674540' },
  { brand: 'Vallejo', ref: '70.829', name: 'Amaranth Red', range: 'Model Color', hex: '#d24e31' },
  { brand: 'Vallejo', ref: '70.830', name: 'Ger. Fieldgrey WWII', range: 'Model Color', hex: '#565239' },
  { brand: 'Vallejo', ref: '70.833', name: 'Fern Green', range: 'Model Color', hex: '#445634' },
  { brand: 'Vallejo', ref: '70.835', name: 'Salmon Rose', range: 'Model Color', hex: '#e18e7c' },
  { brand: 'Vallejo', ref: '70.836', name: 'London Grey', range: 'Model Color', hex: '#696362' },
  { brand: 'Vallejo', ref: '70.837', name: 'Pale Sand', range: 'Model Color', hex: '#e3c28d' },
  { brand: 'Vallejo', ref: '70.838', name: 'Emerald', range: 'Model Color', hex: '#006249' },
  { brand: 'Vallejo', ref: '70.840', name: 'Light Turquoise', range: 'Model Color', hex: '#00688b' },
  { brand: 'Vallejo', ref: '70.841', name: 'Andrea Blue', range: 'Model Color', hex: '#0071ad' },
  { brand: 'Vallejo', ref: '70.843', name: 'Cork Brown', range: 'Model Color', hex: '#a0704e' },
  { brand: 'Vallejo', ref: '70.844', name: 'Deep Sky Blue', range: 'Model Color', hex: '#4d95c4' },
  { brand: 'Vallejo', ref: '70.845', name: 'Sunny Skin Tone', range: 'Model Color', hex: '#ec9745' },
  { brand: 'Vallejo', ref: '70.846', name: 'Mahogany Brown', range: 'Model Color', hex: '#784d47' },
  { brand: 'Vallejo', ref: '70.847', name: 'Dark Sand', range: 'Model Color', hex: '#cba665' },
  { brand: 'Vallejo', ref: '70.850', name: 'Medium Olive', range: 'Model Color', hex: '#404e31' },
  { brand: 'Vallejo', ref: '70.851', name: 'Bright Orange', range: 'Model Color', hex: '#de5a21' },
  { brand: 'Vallejo', ref: '70.856', name: 'Ochre Brown', range: 'Model Color', hex: '#aa793e' },
  { brand: 'Vallejo', ref: '70.858', name: 'Ice Yellow', range: 'Model Color', hex: '#eccf70' },
  { brand: 'Vallejo', ref: '70.859', name: 'Black Red', range: 'Model Color', hex: '#552f2b' },
  { brand: 'Vallejo', ref: '70.860', name: 'Med. Flesh Tone', range: 'Model Color', hex: '#b0793f' },
  { brand: 'Vallejo', ref: '70.861', name: 'Gloss Black', range: 'Model Color', hex: '#241e1f' },
  { brand: 'Vallejo', ref: '70.862', name: 'Black Grey', range: 'Model Color', hex: '#2f2722' },
  { brand: 'Vallejo', ref: '70.866', name: 'Grey Green', range: 'Model Color', hex: '#423f3d' },
  { brand: 'Vallejo', ref: '70.867', name: 'Dark Blue Grey', range: 'Model Color', hex: '#424346' },
  { brand: 'Vallejo', ref: '70.868', name: 'Dark Sea Green', range: 'Model Color', hex: '#4b4546' },
  { brand: 'Vallejo', ref: '70.869', name: 'Basalt Grey', range: 'Model Color', hex: '#5c595d' },
  { brand: 'Vallejo', ref: '70.870', name: 'Medium Sea Grey', range: 'Model Color', hex: '#7d7b7b' },
  { brand: 'Vallejo', ref: '70.871', name: 'Leather Brown', range: 'Model Color', hex: '#594435' },
  { brand: 'Vallejo', ref: '70.872', name: 'Chocolate Brown', range: 'Model Color', hex: '#604e45' },
  { brand: 'Vallejo', ref: '70.873', name: 'US Field Drab', range: 'Model Color', hex: '#816645' },
  { brand: 'Vallejo', ref: '70.874', name: 'Tan Earth', range: 'Model Color', hex: '#987558' },
  { brand: 'Vallejo', ref: '70.875', name: 'Beige Brown', range: 'Model Color', hex: '#815f43' },
  { brand: 'Vallejo', ref: '70.876', name: 'Brown Sand', range: 'Model Color', hex: '#916144' },
  { brand: 'Vallejo', ref: '70.877', name: 'Gold Brown', range: 'Model Color', hex: '#bf873c' },
  { brand: 'Vallejo', ref: '70.879', name: 'Green Brown', range: 'Model Color', hex: '#816c31' },
  { brand: 'Vallejo', ref: '70.880', name: 'Khaki Grey', range: 'Model Color', hex: '#7c6338' },
  { brand: 'Vallejo', ref: '70.881', name: 'Green Yellow', range: 'Model Color', hex: '#6f653c' },
  { brand: 'Vallejo', ref: '70.882', name: 'Middle Stone', range: 'Model Color', hex: '#937f40' },
  { brand: 'Vallejo', ref: '70.883', name: 'Silver Grey', range: 'Model Color', hex: '#d7cfc6' },
  { brand: 'Vallejo', ref: '70.884', name: 'Stone Grey', range: 'Model Color', hex: '#8a7d64' },
  { brand: 'Vallejo', ref: '70.885', name: 'Pastel Green', range: 'Model Color', hex: '#94976f' },
  { brand: 'Vallejo', ref: '70.886', name: 'Green Grey', range: 'Model Color', hex: '#65634f' },
  { brand: 'Vallejo', ref: '70.887', name: 'US Olive Drab', range: 'Model Color', hex: '#58523c' },
  { brand: 'Vallejo', ref: '70.888', name: 'Olive Grey', range: 'Model Color', hex: '#42412d' },
  { brand: 'Vallejo', ref: '70.889', name: 'Olive Brown', range: 'Model Color', hex: '#3f3127' },
  { brand: 'Vallejo', ref: '70.890', name: 'Refractive Green', range: 'Model Color', hex: '#464834' },
  { brand: 'Vallejo', ref: '70.891', name: 'Intermediate Green', range: 'Model Color', hex: '#506642' },
  { brand: 'Vallejo', ref: '70.892', name: 'Yellow Olive', range: 'Model Color', hex: '#383b30' },
  { brand: 'Vallejo', ref: '70.893', name: 'US Dark Green', range: 'Model Color', hex: '#4a4938' },
  { brand: 'Vallejo', ref: '70.894', name: 'Cam. Olive Green', range: 'Model Color', hex: '#3d3b2e' },
  { brand: 'Vallejo', ref: '70.895', name: 'Gunship Green', range: 'Model Color', hex: '#4c5841' },
  { brand: 'Vallejo', ref: '70.896', name: 'Extra Dark Green', range: 'Model Color', hex: '#2a2a14' },
  { brand: 'Vallejo', ref: '70.897', name: 'Bronze Green', range: 'Model Color', hex: '#313a28' },
  { brand: 'Vallejo', ref: '70.898', name: 'Dark Sea Blue', range: 'Model Color', hex: '#272d38' },
  { brand: 'Vallejo', ref: '70.899', name: 'Dark Prussian Blue', range: 'Model Color', hex: '#262539' },
  { brand: 'Vallejo', ref: '70.901', name: 'Pastel Blue', range: 'Model Color', hex: '#607a91' },
  { brand: 'Vallejo', ref: '70.902', name: 'Azure', range: 'Model Color', hex: '#5b6b9e' },
  { brand: 'Vallejo', ref: '70.905', name: 'Blue Grey Pale', range: 'Model Color', hex: '#818586' },
  { brand: 'Vallejo', ref: '70.906', name: 'Pale Blue', range: 'Model Color', hex: '#90a3a7' },
  { brand: 'Vallejo', ref: '70.907', name: 'Pale Grey Blue', range: 'Model Color', hex: '#a8b5b5' },
  { brand: 'Vallejo', ref: '70.908', name: 'Carmine Red', range: 'Model Color', hex: '#96211e' },
  { brand: 'Vallejo', ref: '70.909', name: 'Vermilion', range: 'Model Color', hex: '#c42a28' },
  { brand: 'Vallejo', ref: '70.911', name: 'Light Orange', range: 'Model Color', hex: '#ee7326' },
  { brand: 'Vallejo', ref: '70.913', name: 'Yellow Ochre', range: 'Model Color', hex: '#deaa46' },
  { brand: 'Vallejo', ref: '70.914', name: 'Green Ochre', range: 'Model Color', hex: '#a07f37' },
  { brand: 'Vallejo', ref: '70.915', name: 'Deep Yellow', range: 'Model Color', hex: '#f0c700' },
  { brand: 'Vallejo', ref: '70.916', name: 'Sand Yellow', range: 'Model Color', hex: '#eac054' },
  { brand: 'Vallejo', ref: '70.917', name: 'Beige', range: 'Model Color', hex: '#e0be6d' },
  { brand: 'Vallejo', ref: '70.918', name: 'Ivory', range: 'Model Color', hex: '#eae2d2' },
  { brand: 'Vallejo', ref: '70.919', name: 'Cold White', range: 'Model Color', hex: '#f6f5f9' },
  { brand: 'Vallejo', ref: '70.920', name: 'German Uniform', range: 'Model Color', hex: '#434f42' },
  { brand: 'Vallejo', ref: '70.921', name: 'English Uniform', range: 'Model Color', hex: '#6f532b' },
  { brand: 'Vallejo', ref: '70.922', name: 'Uniform Green', range: 'Model Color', hex: '#48542f' },
  { brand: 'Vallejo', ref: '70.923', name: 'Japan. Unif. WWII', range: 'Model Color', hex: '#9f802a' },
  { brand: 'Vallejo', ref: '70.924', name: 'Russian Unif. WWII', range: 'Model Color', hex: '#545235' },
  { brand: 'Vallejo', ref: '70.925', name: 'Blue', range: 'Model Color', hex: '#372c4b' },
  { brand: 'Vallejo', ref: '70.926', name: 'Red', range: 'Model Color', hex: '#7a2826' },
  { brand: 'Vallejo', ref: '70.927', name: 'Dark Flesh', range: 'Model Color', hex: '#d2933a' },
  { brand: 'Vallejo', ref: '70.928', name: 'Light Flesh', range: 'Model Color', hex: '#f3d4b8' },
  { brand: 'Vallejo', ref: '70.929', name: 'Light Brown', range: 'Model Color', hex: '#a15b31' },
  { brand: 'Vallejo', ref: '70.930', name: 'Dark Blue', range: 'Model Color', hex: '#273462' },
  { brand: 'Vallejo', ref: '70.939', name: 'Smoke Ink', range: 'Model Color', hex: '#5d4944' },
  { brand: 'Vallejo', ref: '70.940', name: 'Saddle Brown', range: 'Model Color', hex: '#8b655b' },
  { brand: 'Vallejo', ref: '70.941', name: 'Burnt Umber', range: 'Model Color', hex: '#513b30' },
  { brand: 'Vallejo', ref: '70.943', name: 'Grey Blue', range: 'Model Color', hex: '#596e84' },
  { brand: 'Vallejo', ref: '70.944', name: 'Old Rose', range: 'Model Color', hex: '#bc6e6f' },
  { brand: 'Vallejo', ref: '70.945', name: 'Magenta', range: 'Model Color', hex: '#903055' },
  { brand: 'Vallejo', ref: '70.946', name: 'Dark Red', range: 'Model Color', hex: '#692f25' },
  { brand: 'Vallejo', ref: '70.947', name: 'Dark Vermilion', range: 'Model Color', hex: '#b52a27' },
  { brand: 'Vallejo', ref: '70.948', name: 'Golden Yellow', range: 'Model Color', hex: '#f7a833' },
  { brand: 'Vallejo', ref: '70.949', name: 'Light Yellow', range: 'Model Color', hex: '#f7d346' },
  { brand: 'Vallejo', ref: '70.950', name: 'Black', range: 'Model Color', hex: '#231c1d' },
  { brand: 'Vallejo', ref: '70.951', name: 'White', range: 'Model Color', hex: '#ffffff' },
  { brand: 'Vallejo', ref: '70.952', name: 'Lemon Yellow', range: 'Model Color', hex: '#e6d203' },
  { brand: 'Vallejo', ref: '70.953', name: 'Flat Yellow', range: 'Model Color', hex: '#f6ba35' },
  { brand: 'Vallejo', ref: '70.954', name: 'Yellow Green', range: 'Model Color', hex: '#dedd26' },
  { brand: 'Vallejo', ref: '70.955', name: 'Flat Flesh', range: 'Model Color', hex: '#df9a59' },
  { brand: 'Vallejo', ref: '70.956', name: 'Clear Orange', range: 'Model Color', hex: '#cc4625' },
  { brand: 'Vallejo', ref: '70.957', name: 'Flat Red', range: 'Model Color', hex: '#a12b28' },
  { brand: 'Vallejo', ref: '70.958', name: 'Pink', range: 'Model Color', hex: '#b14e7c' },
  { brand: 'Vallejo', ref: '70.959', name: 'Purple', range: 'Model Color', hex: '#533153' },
  { brand: 'Vallejo', ref: '70.960', name: 'Violet', range: 'Model Color', hex: '#3c2c4b' },
  { brand: 'Vallejo', ref: '70.961', name: 'Sky Blue', range: 'Model Color', hex: '#75b7d0' },
  { brand: 'Vallejo', ref: '70.962', name: 'Flat Blue', range: 'Model Color', hex: '#3f4874' },
  { brand: 'Vallejo', ref: '70.963', name: 'Medium Blue', range: 'Model Color', hex: '#16416d' },
  { brand: 'Vallejo', ref: '70.964', name: 'Field Blue', range: 'Model Color', hex: '#4d5257' },
  { brand: 'Vallejo', ref: '70.965', name: 'Prussian Blue', range: 'Model Color', hex: '#39415d' },
  { brand: 'Vallejo', ref: '70.966', name: 'Turquoise', range: 'Model Color', hex: '#0e425b' },
  { brand: 'Vallejo', ref: '70.967', name: 'Olive Green', range: 'Model Color', hex: '#506237' },
  { brand: 'Vallejo', ref: '70.968', name: 'Flat Green', range: 'Model Color', hex: '#364b2d' },
  { brand: 'Vallejo', ref: '70.969', name: 'Park Green Flat', range: 'Model Color', hex: '#1f634a' },
  { brand: 'Vallejo', ref: '70.970', name: 'Deep Green', range: 'Model Color', hex: '#1c4c2f' },
  { brand: 'Vallejo', ref: '70.971', name: 'Light Green Grey', range: 'Model Color', hex: '#b4b5ab' },
  { brand: 'Vallejo', ref: '70.972', name: 'Light Green Blue', range: 'Model Color', hex: '#86968e' },
  { brand: 'Vallejo', ref: '70.974', name: 'Green Sky', range: 'Model Color', hex: '#799165' },
  { brand: 'Vallejo', ref: '70.975', name: 'Military Green', range: 'Model Color', hex: '#434234' },
  { brand: 'Vallejo', ref: '70.976', name: 'Buff', range: 'Model Color', hex: '#d6b04e' },
  { brand: 'Vallejo', ref: '70.977', name: 'Desert Yellow', range: 'Model Color', hex: '#b58547' },
  { brand: 'Vallejo', ref: '70.978', name: 'Dark Yellow', range: 'Model Color', hex: '#918739' },
  { brand: 'Vallejo', ref: '70.979', name: 'Cam. Dark Green', range: 'Model Color', hex: '#263122' },
  { brand: 'Vallejo', ref: '70.980', name: 'Black Green', range: 'Model Color', hex: '#28352a' },
  { brand: 'Vallejo', ref: '70.981', name: 'Orange Brown', range: 'Model Color', hex: '#ac633a' },
  { brand: 'Vallejo', ref: '70.982', name: 'Cavalry Brown', range: 'Model Color', hex: '#854438' },
  { brand: 'Vallejo', ref: '70.983', name: 'Flat Earth', range: 'Model Color', hex: '#684429' },
  { brand: 'Vallejo', ref: '70.984', name: 'Flat Brown', range: 'Model Color', hex: '#6f4037' },
  { brand: 'Vallejo', ref: '70.985', name: 'Hull Red', range: 'Model Color', hex: '#5e3838' },
  { brand: 'Vallejo', ref: '70.986', name: 'Deck Tan', range: 'Model Color', hex: '#aaa390' },
  { brand: 'Vallejo', ref: '70.987', name: 'Medium Grey', range: 'Model Color', hex: '#867259' },
  { brand: 'Vallejo', ref: '70.988', name: 'Khaki', range: 'Model Color', hex: '#786538' },
  { brand: 'Vallejo', ref: '70.989', name: 'Sky Grey', range: 'Model Color', hex: '#a9aaab' },
  { brand: 'Vallejo', ref: '70.990', name: 'Light Grey', range: 'Model Color', hex: '#8f9293' },
  { brand: 'Vallejo', ref: '70.991', name: 'Dark Sea Grey', range: 'Model Color', hex: '#6c6b6a' },
  { brand: 'Vallejo', ref: '70.992', name: 'Neutral Grey', range: 'Model Color', hex: '#61605f' },
  { brand: 'Vallejo', ref: '70.993', name: 'White Grey', range: 'Model Color', hex: '#e4e0de' },
  { brand: 'Vallejo', ref: '70.994', name: 'Dark Grey', range: 'Model Color', hex: '#322e34' },
  { brand: 'Vallejo', ref: '70.995', name: 'German Grey', range: 'Model Color', hex: '#2d2e2b' },
]
